NethServer/ns8-core

core/imageroot/usr/local/bin/extract-image, core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update, core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/10validate, core/imageroot/var/lib/nethserver/cluster/actions/remove-module/50update, core/imageroot/var/lib/nethserver/node/actions/add-module/50update, core/install.sh, samba/build-image.sh
A module can require one or more TCP ports allocation with the
"org.nethserver/tcp_ports_demand" image label. For instance
org.nethserver/tcp_ports_demand=3
It means the module receives a range of three TCP port numbers in the
usual module environment, where the following variables are set
- `TCP_PORT=1001` (always set to the range first port)
- `TCP_PORTS_RANGE=1001-1003` (the full range, if more than one port is allocated)
- `TCP_PORTS=1001,1002,1003` (comma-separated list of port numbers, if no more than 8 ports are allocated)
=> Allocate one or more TCP ports

.github/workflows/samba.yml, core/imageroot/usr/local/bin/podman-pull-missing, core/imageroot/var/lib/nethserver/node/actions/add-module/50update, doc/new_module.md, samba/build-image.sh, samba/imageroot/actions/create-module/50initialize, samba/imageroot/actions/provision-domain/70start_provisioning, samba/imageroot/samba-dc.service
1. Use the `org.nethserver/rootful=1` label
2. Automated builds
3. Generate the additional `samba-dc` image
3. Do not use `org.nethserver/imageroot=/srv/imageroot` label any more
=> New Samba images layout and automated build

core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
An user with "owner" role on "cluster" inherits the same role on added modules.
=> Inherit the "owner" role

core/api-server/methods/auth.go, core/imageroot/usr/local/nethserver/agent/python/cluster/grants.py, core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/remove-user/50update
Store the per-user module/role map in Redis DB keys like "roles/{user}".
The "user/*" key pattern is reserved to other user information, like display name, email...
=> Changed roles/* keys prefix

core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/50update, core/imageroot/var/lib/nethserver/cluster/actions/join-cluster/50update, core/imageroot/var/lib/nethserver/node/uninstall.sh, core/install.sh
The `cluster-localnode` /etc/hosts record points to the node VPN IP address. It is designed to bind local daemons to the VPN IP address.
On system boot, ensure the daemon is started after the VPN is up.
The same IP address can be retrieved from Redis too, using the new `NODE_ID` environment variable. Some code examples:
Bash
```bash
redis-exec HGET node/${NODE_ID}/vpn ip_address
```
Python
```python
import os, agent
rdb = agent.redis_connect()
ip_address = rdb.hget(f'node/{os.environ["NODE_ID"]}/vpn', 'ip_address')
```
=> Set cluster-localnode in /etc/hosts

core/agent/action/action.go, core/agent/agent.go, core/agent/go.mod, core/agent/go.sum, core/agent/test.sh, core/agent/test/30output, core/agent/test/validate-input.json, core/agent/test/validate-output.json, core/agent/validation/validation.go, core/imageroot/var/lib/nethserver/cluster/actions/add-user/50update, core/imageroot/var/lib/nethserver/cluster/actions/add-user/validate-input.json, core/imageroot/var/lib/nethserver/cluster/actions/add-user/validate-output.json, core/imageroot/var/lib/nethserver/cluster/validator-definitions.json
Optionally validate the action input and output with JSON Schema.
- https://json-schema.org/specification.html
- https://json-schema.org/understanding-json-schema/index.html
Schema files are loaded from special paths:
1) `${AGENT_INSTALL_DIR}/validator-definitions.json` . This is always picked up by the agent from all actions. It can contain the common data format definitions
2) ` ${AGENT_INSTALL_DIR}/actions/<action-name>/validate-input.json`. Schema applied to validate the Task input data
3) ` ${AGENT_INSTALL_DIR}/actions/<action-name>/validate-output.json`. Schema applied to validate the Task output data
This pull request ships JSON Schema files to validate `add-user` input.
=> Validate Task data with JSON Schema

.github/workflows/loki.yml, core/build-image.sh, core/imageroot/etc/profile.d/nethserver.sh, core/imageroot/var/lib/nethserver/cluster/state/images-catalog.txt, core/imageroot/var/lib/nethserver/node/logcli.sh, loki/README.md, loki/build-image.sh, loki/imageroot/actions/create-module/10env, loki/imageroot/actions/create-module/10expandconfig, loki/imageroot/actions/create-module/10pull_image, loki/imageroot/actions/create-module/20systemd, loki/imageroot/systemd/user/loki-server.service, loki/imageroot/systemd/user/loki.service, loki/imageroot/systemd/user/traefik.service, loki/ui/index.html, promtail/imageroot/actions/create-module/20initialize
Loki is a log aggregation system, main project site: https://grafana.com/oss/loki/
This PR adds two new components:
* `logcli`, a cli tool for query the Loki server for logs
* `loki`, the server that will receive, and store the logs
As default, the Loki server will listen on the IP address of the node's VPN interface, using the default fixed port `3100`.
The agents `promtail` and the clients `logcli` will assume that the default Loki server to use, is installed on the cluster leader node.
What is not present in this PR and is left for further work:
* Loki server port reservation
* HTTPS certificate and path reservation in the main host, (currently the `traefik` module don't allow this)
* Authentication for sending and querying logs
* A way to make visible at cluster level the default …
=> Add Loki module

core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, ldapproxy/build-image.sh, samba/build-image.sh, traefik/build-image.sh, traefik/imageroot/actions/create-module/10expandconfig, traefik/imageroot/actions/create-module/10pullimage, traefik/imageroot/actions/create-module/30grants
1. New image label definition: `register_default_instance`
A new module instance can ask to be registered as "first instance of module"
at cluster and node level. This information is useful to discover other
modules and establish default behaviors when further module instances are installed.
Modules providing services to other modules are the target of this new feature.
2. Execute actions returned by create-module
When a module instance is created a list of special actions can be fired to complete the setup.
- The list is returned by the module "create-module" action.
- The actions are executed by targeted agents after an authorization check.
- Authorized actions must be member of the `AGENT_ID/roles/create-module` Redis set
A target Agent is identified with the following values
- …
=> Default information and actions for new modules

core/install.sh, doc/installation.md
> Developers may prefer to run install.sh with one or more images from a development branch. The first argument selects the branch name, following arguments the module names to be pulled from that branch.
bash install.sh mybranch module1 module2 ...
=> Specify branch name to install from

core/imageroot/etc/nethserver/pythonreq.txt, core/imageroot/usr/local/nethserver/agent/python/agent/__init__.py, core/imageroot/usr/local/nethserver/agent/python/agent/tasks.py, core/imageroot/usr/local/sbin/update-routes, core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update, core/imageroot/var/lib/nethserver/cluster/actions/add-node/validate-output.json, core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/50update, core/imageroot/var/lib/nethserver/cluster/actions/join-cluster/50update, core/imageroot/var/lib/nethserver/node/actions/update-routes/50update, core/imageroot/var/lib/nethserver/node/actions/update-routes/validate-input.json, core/imageroot/var/lib/nethserver/node/actions/update-routes/validate-output.json, core/imageroot/var/lib/nethserver/node/validator-definitions.json, core/install.sh
Implement a basic API to route custom destinations through the cluster VPN and reconfigure VPN routes when a new node is added to the cluster.
- ~~`add-route`: add a destination (in CIDR notation) for the given node_id~~ moved to another PR
- ~~`remove-route`~~ moved to another PR
- `update-routes`: read the VPN configuration from Redis and apply it to the current node. Helper command `update-routes` is also in the bundle for manual invocation.
To implement the above API a new set of functions has been added: the `agent.tasks` module was extended with new tasks invocation styles:
- support `endpoint='redis://cluster-leader'`, really useful for cluster actions because it bypasses the api-server auditing
- `runp()` run a list of task in parallel
- `runp_nowait()` as above, but does not wait …
=> Reconfigure VPN with update-routes action

core/imageroot/etc/systemd/system/eventsgw@.service, core/imageroot/etc/systemd/user/eventsgw.service, core/imageroot/usr/local/bin/eventsgw, core/imageroot/usr/local/nethserver/agent/actions/create-module/90start_eventsgw, core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update, core/install.sh
A module can run its `eventsgw.service` unit to translate Redis keyspace and PUB/SUB events into action calls.
The service is configured by putting a `eventsgw.conf` file in the agent state dir. The service must be enabled and started (probably in the create-module action or similar).
Sample  `eventsgw.conf` file:
```ini
[commands]
module/traefik1/event/certificate-update = redis-exec INCR mykey
[actions]
__keyspace@0__:testkey = change-testkey
module/traefik1/event/certificate-update = update-certificate
module/traefik*/event/certificate-renew = renew-certificate
```
=> Redis events gateway for agents

core/imageroot/etc/profile.d/nethserver.sh
The pathmunge funtion is provided by Fedora/RHEL bash profile
Avoid errors on `ssh <module_id>@localhost`:
pathmunge: command not found
=> debian: define pathmunge

traefik/imageroot/actions/create-module/50create, traefik/imageroot/systemd/user/certificate-exporter.path, traefik/imageroot/systemd/user/certificate-exporter.service, traefik/imageroot/systemd/user/traefik.service
On Fedora the traefik1 module fails to start due to a dependency cycle:
```
-- Boot d8e1080499614b0599ce0a112a817125 --
Jul 22 08:53:06 fc1.dp.nethserver.net systemd[692]: certificate-exporter.path: Found ordering cycle on traefik.service/start
Jul 22 08:53:06 fc1.dp.nethserver.net systemd[692]: certificate-exporter.path: Found dependency on basic.target/start
Jul 22 08:53:06 fc1.dp.nethserver.net systemd[692]: certificate-exporter.path: Found dependency on paths.target/start
Jul 22 08:53:06 fc1.dp.nethserver.net systemd[692]: certificate-exporter.path: Found dependency on certificate-exporter.path/start
Jul 22 08:53:06 fc1.dp.nethserver.net systemd[692]: certificate-exporter.path: Job traefik.service/start deleted to break ordering cycle starting with certificate-exporter.path/start
``` …
=> Fix unit startup order on Fedora

core/imageroot/usr/local/nethserver/agent/python/agent/__init__.py, core/imageroot/usr/local/nethserver/agent/python/agent/tasks.py, core/imageroot/usr/local/nethserver/agent/python/cluster/grants.py, core/imageroot/usr/local/sbin/add-module, core/imageroot/usr/local/sbin/add-user, core/imageroot/usr/local/sbin/create-cluster, core/imageroot/usr/local/sbin/grant-actions, core/imageroot/usr/local/sbin/join-cluster, core/imageroot/usr/local/sbin/remove-module, core/imageroot/usr/local/sbin/remove-user, core/imageroot/usr/local/sbin/revoke-actions, core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/remove-module/50update
Obsoleted by agent.tasks.run()
The new implementation catches the task completion with Redis SUBSCRIBE
or via HTTP websocket. This is faster and more robust than the 1 second
polling loop.
Future enhancements to agent.tasks will catch also timeouts and more
connection issues.
The `agent.tasks` Python module also provides some variants for parallel tasks execution
- runp() - run parallel tasks
- runp_brief() - run parallel tasks, return the number of failed tasks only. Log to stderr
- runp_nowait() - run parallel tasks, return immediately the a list of task IDs
=> Remove agent.run_subtask() function

core/imageroot/var/lib/nethserver/cluster/actions/remove-module/50update
When a module instance is removed check if it is considered a *default_instance*. Clean up the Redis default_instance key if required.
=> Clean up default_instance on module removal

core/install.sh, doc/installation.md, traefik/README.md, traefik/imageroot/actions/create-module/10expandconfig, traefik/imageroot/actions/delete-certificate/20writeconfig, traefik/imageroot/actions/delete-certificate/validate-input.json, traefik/imageroot/actions/delete-certificate/validate-output.json, traefik/imageroot/actions/set-certificate/20writeconfig, traefik/imageroot/actions/set-certificate/validate-input.json, traefik/imageroot/actions/set-certificate/validate-output.json, traefik/imageroot/bin/export-certificate
This PR adds two new actions to traefik for explicitly request a Let's Encrypt certificate for a node, new actions:
* `set-certificate`
* `delete-certificate`
Other changes:
- document how to access the UI
- document how the UI can be accessed using a valid certificate, if Let's Encrypt requirements are met
=> traefik: explicit request LE certificate for an FQDN

ldapproxy/README.md, ldapproxy/imageroot/actions/restart-service/50restart, ldapproxy/imageroot/actions/set-backend/50update, ldapproxy/imageroot/actions/set-backend/validate-input.json, ldapproxy/imageroot/nginx.conf.template, samba/README.md, samba/imageroot/actions/provision-domain/05set_env, samba/imageroot/actions/provision-domain/40start_provisioning, samba/imageroot/actions/provision-domain/50set_backend, samba/scripts/entrypoint.sh
Create the `ldapservice` account in AD and publish its credentials in Redis, as environment variables of Ldapproxy.
Applications can use `ldapservice` credentials to authenticate LDAP connections and browse the LDAP tree.
Additional environment variables are defined for Ldapproxy, to connect with the LDAP service.
See the modified README.md files for usage information.
=> Ldapservice account for LDAP binds

traefik/README.md
- fix syntax
- use `hostname -f` for easy cut&paste
=> traefik: improve readme example syntax

core/imageroot/usr/local/bin/eventsgw, core/imageroot/usr/local/nethserver/agent/python/agent/__init__.py, core/imageroot/usr/local/nethserver/agent/python/agent/tasks.py, core/imageroot/var/lib/nethserver/cluster/actions/join-cluster/50update, core/install.sh, doc/details.md
Redis credentials are stored in REDIS_USER and REDIS_PASSWORD environment variables. However the cluster and node agents are missing REDIS_USER, so the actual code implementation fall back to AGENT_ID if REDIS_USER is missing.
This PR aligns the cluster and node agents environment to other modules, and eliminates the need of the fall back code.
=> Clean up AGENT_ID fallback code

core/imageroot/usr/local/bin/api-cli, doc/details.md, doc/installation.md, dokuwiki/README.md, ldapproxy/README.md, samba/README.md, traefik/README.md
- login/logout, with disk token cache (requires a sane session
environment)
- run (alias, submit) actions waiting for the task response (--nowait
provided too)
Synopsis:
```
$ api-cli --help
usage: api-cli [-h] [--endpoint ENDPOINT] [--no-tlsverify] {login,logout,run,submit} ...
Invoke cluster APIs from the command line
optional arguments:
-h, --help            show this help message and exit
--endpoint ENDPOINT   override the library default endpoint URL
--no-tlsverify        do not verify TLS certificate of HTTPS endpoint
commands:
{login,logout,run,submit}
login               authenticate with the remote server
logout              clean up the authorization token disk cache
run (submit)        submit a task to the remote server and print the results
```
1. obtain an authorization token …
=> Api-cli command implementation

core/api-server/go.mod, core/api-server/go.sum, core/api-server/socket/socket.go
Solve security vulnerability by replacing `github.com/dgrijalva/jwt-go` with `github.com/golang-jwt/jwt`
- Use `go mod tidy` to cleanup unused dependency
https://github.com/advisories/GHSA-w73w-5m7g-f7qc
=> api. fix CVE-2020-26160

core/imageroot/var/lib/nethserver/cluster/actions/change-user-password/50update, core/imageroot/var/lib/nethserver/cluster/actions/change-user-password/validate-input.json, core/imageroot/var/lib/nethserver/cluster/actions/change-user-password/validate-output.json
The UI can now change the password on first run
=> core api: add change-user-password

core/imageroot/usr/local/bin/extract-image, core/imageroot/usr/local/nethserver/agent/actions/update-module/05pullimages, core/imageroot/usr/local/nethserver/agent/actions/update-module/50run_scriptdir, core/imageroot/usr/local/nethserver/agent/actions/update-module/90eventsgw_restart, core/imageroot/usr/local/nethserver/agent/actions/update-module/validate-input.json, core/imageroot/var/lib/nethserver/cluster/actions/update-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/update-module/validate-input.json
- new `update-module` cluster action. Input example:
{
"module_url": "ghcr.io/nethserver/mymodule:3.2.2",
"instances": [
"mymodule2",
"mymodule3"
]
}
- Each module instance is responsible for updating itself. The core provides an extendable implementation of the `update-module` action for the **module agent**. The basic implementation 
- pulls the module image and additional service images, 
- updates the environment variables, keeping track of PREV_* values
- extracts and installs the module _imageroot_ under the AGENT_INSTALL_DIR, 
- performs `systemctl daemon-reload`
- Added _old files removal_ capability to `extract-image` helper. New image files overwrite the existing ones: it is also necessary to clean up files and (empty) dirs that are no longer required.
=> Module updates

core/imageroot/usr/local/agent/pypkg/agent/__init__.py, core/imageroot/usr/local/bin/runagent
The "source" of environment files is fragile: if they contain special
shell chars, like "&" the parsing fails.
Read environment files and export the environment variables
without importing them in Bash, thus special chars are not considered.
Changed `agent.read_envfile()`: values of variables are stored in raw form, no shell-like special chars escaping and transformations are needed.
=> Protect runagent from special shell chars

README.md
The folder name has changed `s/doc/docs/` We have a 404 issue when I try to browse the webpage
=> Solve 404 issues

.github/workflows/core.yml, core/build-image.sh
- Save Golang modules and build cache
- Save buildah overlay-images directory
The cache expires every Sunday, and is invalidated if go.sum go.mod yarn.lock and build-image.sh are modified.
For instance, this is a cache key:
Cache restored from key: corecache-2021W45-715a07faf8426d54f9d1d207433c1cbff9c762f8cb1a73e6784442eb2f9b736b
See also https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
=> Store more artifacts in the core build cache

core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/add-module/validate-input.json, core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
Disable idle check during add-node. The node agent is surely not
running until add-node returns.
=> Fix add-module failures due to idle checks

dokuwiki/imageroot/actions/configure-module/20configure
We save a default `user_full_name` to `env` and not the data['user_full_name'] value
=> Save the correct value for administrator full name

.github/workflows/images_cleanup.yml
When a PR is closed this workflow will remove the relatives images tags generated from that PR, for correctly working a new Github Personal Access Token is added and stored in the secret `IMAGES_CLEANUP_TOKEN`.
The token must have the following permission:
* `packages:read`
* `packages:delete`
The users associated with the PAT must have admin permission over the containers.
https://docs.github.com/en/rest/reference/packages#delete-package-version-for-an-organization
=> actions: add an images cleanup workflow

core/install.sh
Sometimes, `journalctl` is not correctly displaying the messages.
This is has been tested on a Debian 11 running on Digital Ocean:
```
No journal files were found.
-- No entries --
```
The fix:
```
```
Outcome:
```
-- Journal begins at Fri 2022-02-11 13:15:51 UTC, ends at Fri 2022-02-11 13:15:51 UTC. --
Feb 11 13:15:51 debian-s-1vcpu-1gb-intel-lon1-01 systemd[1]: Stopping Journal Service...
Feb 11 13:15:51 debian-s-1vcpu-1gb-intel-lon1-01 systemd-journald[222]: Received SIGTERM from PID 1 (systemd).
Feb 11 13:15:51 debian-s-1vcpu-1gb-intel-lon1-01 systemd[1]: systemd-journald.service: Succeeded.
...
```
=> install.sh: restart journald

core/imageroot/usr/local/agent/bin/module-restore
Remount AGENT_INSTALL_DIR to /srv, to allow restoring files outside of Podman volumes.
=> core. Restore files in module file system

core/imageroot/usr/local/agent/pypkg/cluster/modules.py, core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/list-backups/50list, core/imageroot/var/lib/nethserver/cluster/actions/list-installed-modules/validate-output.json, ldapproxy/build-image.sh, loki/build-image.sh, promtail/build-image.sh, samba/build-image.sh
Flags are a new image label named `org.nethserver.flags`.
It contains a space separated list of flags with known values.
Flags can be used to mark modules inside the UI and eventually enforce module behavior.
Currently available flags are:    
- `core_module`
- `account_provider`
- `no_data_backup`
- `rootless` (calculated from `org.nethserver.rootfull` label)
- `rootfull` (calculated from `org.nethserver.rootfull` label)
=> Add module flags

samba/imageroot/actions/restore-module/02samba_device, samba/imageroot/bin/expand_dns_forwarder, samba/imageroot/bin/samba-network, samba/imageroot/etc/samba-dc.service, samba/scripts/entrypoint.sh
If Samba is restored on a different hardware:
1. the IPADDRESS could be missing
2. dns forwarder may be different
This PR ensures that IPADDRESS can always be found, by creating a dummy network interface on the fly, if requested.
Furthermore, whenever samba starts, the "dns forwarder" Samba option is set to reflect the nameserver list defined in the host /etc/resolv.conf
=> Fix Samba restore preconditions

samba/build-image.sh, samba/imageroot/actions/restore-module/06copyenv, samba/imageroot/actions/restore-module/60resume_state, samba/imageroot/bin/module-cleanup-state, samba/imageroot/bin/module-dump-state, samba/imageroot/etc/state-include.conf
The Samba official restore procedure requires that a new DC host name is
assigned. The host name is generated from the old one, it should be
random enough to avoid collisions.
=> Use official Samba backup/restore tool

core/imageroot/usr/local/agent/actions/create-module/10log_tag, core/tests/10_cluster_sanity/70_check_rootless_modules_logs.robot, core/tests/10_cluster_sanity/71_check_rootfull_modules_logs.robot, ldapproxy/imageroot/systemd/user/ldapproxy.service, loki/imageroot/systemd/user/loki-server.service, loki/imageroot/systemd/user/traefik.service, promtail/imageroot/promtail.service, samba/imageroot/actions/configure-module/40start_provisioning, samba/imageroot/etc/samba-dc.service, traefik/imageroot/systemd/user/traefik.service
- core. add default log tag to rootless modules
- Remove `--log-opt` option from rootless modules
- core, test: add rootless logs tests
- Unified use of `--log-opt` for rootfull modules
- core, test: add rootfull logs tests
=> Refactoring of journal `CONTAINER_TAG` field

core/imageroot/var/lib/nethserver/cluster/actions/clean-repositories-cache/10clean
Force software repository metadata download
Usage:
```
api-cli run clean-repositories-cache
```
See also https://trello.com/c/b6qMwYOT/120-software-center-refresh-metadata
=> api: add clean-repositories-cache

core/imageroot/usr/local/agent/pypkg/agent/tasks/apiclient.py, core/imageroot/usr/local/agent/pypkg/agent/tasks/handlers.py, core/imageroot/usr/local/agent/pypkg/agent/tasks/redisclient.py, core/imageroot/usr/local/agent/pypkg/agent/tasks/run.py, core/install.sh
Execute Python cancel-task handlers in a new context to suppress errors
during async clean up procedures.
The same approach was applied also to the aiohttp client.
=> Fix race conditions during aioredis cleanup

core/imageroot/var/lib/nethserver/node/uninstall.sh
Fix removal of units from rootfull modules in the `uninstall.sh` script.
Refs https://github.com/NethServer/ns8-core/pull/156
=> Cleanup units from rootfull modules

core/imageroot/var/lib/nethserver/cluster/actions/get-cluster-status/50read, core/imageroot/var/lib/nethserver/cluster/actions/get-cluster-status/validate-output.json, core/imageroot/var/lib/nethserver/node/actions/get-info/20read, core/imageroot/var/lib/nethserver/node/actions/get-info/validate-output.json
Add hostname and machine-id to `get-cluster-status` for the API.
The `get-cluster-status` now calls a new node API named `get-info`
=> API: add hostname and machine id to get-cluster-status

core/imageroot/var/lib/nethserver/cluster/actions/get-cluster-status/50read
The cluster/get-cluster-status API crashes when a custom peer is added
to the wg0 interface. If its IP address is not among cluster nodes the
step fails.
=> Fix crash on "guest" VPN peer

core/imageroot/usr/local/agent/actions/get-status/20read, core/imageroot/usr/local/agent/actions/get-status/validate-output.json
The node ui_name is added to the get-status action output.
Fix also the JSON schema with missing information.
=> Add node name to get-status output

core/tests/10_cluster_sanity/80_trefik_check_certificate_apis.robot, traefik/imageroot/actions/create-module/20certificate
If the node's FQDN is used in the default selfsigned certificate, when a valid certificate for the node's FQDN is requested using the `set-certificate` action, `traefik` will not request a new certificate via Let's Encrypt, but will use the already present selfsigned certificate.
This is caused by the fact that in the system is already present a certificate for the requested domain (in the selfsigned certificate) and to avoid this problem the tld `.test` is used in the selfsigned certificate.
The `CN` of the selfsigned certificate will be `FQDN + .test`
=> Fix default HTTPS certificate

core/build-image.sh, core/imageroot/usr/local/agent/actions/clone-module/02pullrsync, core/imageroot/usr/local/agent/actions/clone-module/05create_volumes, core/imageroot/usr/local/agent/actions/clone-module/05replace, core/imageroot/usr/local/agent/actions/clone-module/10recvstate, core/imageroot/usr/local/agent/actions/clone-module/validate-input.json, core/imageroot/usr/local/agent/actions/list-volumes/20list_volumes, core/imageroot/usr/local/agent/actions/list-volumes/validate-output.json, core/imageroot/usr/local/agent/actions/transfer-state/02pullrsync, core/imageroot/usr/local/agent/actions/transfer-state/05waitserver, core/imageroot/usr/local/agent/actions/transfer-state/50sendstate, core/imageroot/usr/local/agent/actions/transfer-state/validate-input.json, core/imageroot/usr/local/agent/bin/redis-dump, core/imageroot/usr/local/agent/bin/redis-restore, core/imageroot/usr/local/agent/pypkg/agent/__init__.py, core/imageroot/var/lib/nethserver/cluster/actions/clone-module/50clone_module, core/imageroot/var/lib/nethserver/cluster/actions/clone-module/validate-input.json, core/rsync/README.md, core/rsync/entrypoint.sh, docs/core/clone_module.md
This PR implements module instance cloning in the `cluster/clone-module` action. As for backup/restore, the clone can be created to replace the original module or not. The `replace` flag controls that behavior.
api-cli run clone-module --data '{"module":"dokuwiki1","replace":false,"node":1}'
- module: original module identifier
- replace: the behavior flag
- node: the identifier of the node where the clone is instantiated
To clone a module instance, the module state files are generated with the module-dump-state/module-cleanup-state commands that are already invoked by backup/restore.
Module state files are transferred to the clone via rsync. The clone runs a rsyncd server, listening on a dedicated TCP port.
Temporary authentication credentials are shared between the origin and clone …
=> Clone a module instance

traefik/imageroot/actions/create-module/20certificate
The `CN` of the self signed certificate was made by concatenating the
`FQDN` of the node with the `.test` tld, this can cause a failure during
the certificate generation if the `FQDN` is already at maximum allowed
length. This was the case with the GitHub Actions runner.
To solve this problem the value of `CN` will be:
* `host-<five random numbers>.ns8.test`
=> traefik: use fixed length `CN` in self signed cert

.github/workflows/tests.yml, core/test-module.sh
Invoke the `tests-module.sh` script instead of manually launching RobotFramework's container.
=> actions: use test-module.sh for start tests

core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
When a module requests 2 or more ports, the TCP_PORT
env variable should contain the first allocated one.
Before this commit, TCP_PORT was set to the last port of the range.
=> add-module: fix port allocation

core/imageroot/usr/local/agent/bin/extract-image, core/imageroot/usr/local/agent/bin/install-coreimage, core/install.sh
GNU "sort" is sensible to the current locale settings. The resulting
coreimage.lst content is unpredictable and causes a file loss during the
core update procedure.
=> Fix update-core action

core/tests/20__cluster_ui/40__software_center.robot
App uninstallation now shows a danger modal: need to type module ID in an input field to confirm uninstallation
=> tests: fix cluster UI / uninstall app test

.github/workflows/core.yml
- Read the branch/tag name from `github.ref_name` context variable
- Do not fall back to "latest". Fail the `buildah push` if IMAGETAG is not properly defined
=> Fix core workflow build

core/imageroot/usr/local/agent/pypkg/cluster/modules.py
Find correct module release if testing is enabled.
If the module is not found, just fail: the exception is propagated to add-module API
=> modules: fix version logic

core/install.sh, core/tests/10__cluster_sanity/_dummy/build-images.sh
The version provided by Debian 11 of the `containers-common` package,
provided as dependence by `podman`, don't have the support for `log-tag`
an option that is needed by the logs system collector.
See: https://github.com/containers/common/commit/6a2f926c6498ce9f76304933354f297dd52302b5
=> install.sh: install podman => 3.4.2

core/tests/20__cluster_ui/20__login.robot, core/tests/20__cluster_ui/40__software_center.robot, core/tests/keywords.resource, core/ui/src/views/SoftwareCenterAppInstances.vue
- If robotframework-browser `Strict Mode` variable is disabled and a UI selector that matches more than one HTML element is used, there is a chance that the wrong element is selected. Let's keep `Strict Mode` enabled and fix the selector in order to select exactly one element
- Support for running UI tests on `localhost`
- Fix variable names case
=> Tests: fix "Uninstall app" UI test

core/imageroot/var/lib/nethserver/node/install-core.sh, core/install.sh
...and a minor tweak for a "Rebase merge"
Journald restart is required to solve test failures on CentOS Stream 9 here https://github.com/NethServer/ns8-terraform-infra/pull/1
=> Install fixes for journald restart

core/imageroot/usr/local/agent/pypkg/agent/ldapproxy.py, core/imageroot/usr/local/agent/pypkg/cluster/userdomains.py
Ldapproxy can now handle domains connected to remote account providers.
See also NethServer/ns8-ldapproxy#3
=> lddaproxy lib: handle external domains

core/imageroot/usr/local/agent/bin/redis-exec
Optimize the multiple commands execution in a single pipeline.
=> Use pipeline mode in redis-exec command

core/imageroot/usr/local/agent/pypkg/cluster/userdomains.py
Existing similar functions receive a Redis opened connection handle
as mandatory argument. The package should not open new connections by
itself.
=> Drop agent package dependency in cluster.userdomains

core/imageroot/etc/systemd/system/agent@.service
If a module has the `-` char, the symbol is replaced with a `/`
generating an invalid agent_id
=> agent systemd unit: fix AGENT_ID

core/imageroot/etc/profile.d/api-cli.sh, core/imageroot/usr/local/bin/api-cli
Since #186 the `api-cli` Bash auto completion is broken. This PR aims to fix it. Refs fb1e605e8f6a440aa03fecbc761f8dbbe4ba2625
The completion token is passed by the Bash function to `api-cli list-actions [prefix]`, as the search `prefix`.
The prefix is used to generate the correct completion list. Only when a full AGENT_ID is completed, the full action list is retrieved with a `list-actions` action call.
=> Fix api-cli auto completion

docs/modules/updates.md, docs/quickstart.md
During development, some local Podman images might override remote ones, producing unexpected behavior.
The typical case is when a `:latest` image tag is used to install/update a module instance that was already downloaded.
=> Add docs note for images in Podman local storage

core/install.sh
Additional packages are incompatible with base installation. An update is
required to fix SELinux policies.
=> Fix CentOS Stream 9 installation

core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/00validate_cluster, core/imageroot/var/lib/nethserver/cluster/actions/join-cluster/00validate_cluster
Fail if the cluster is already configured.
This is just a safeguard measure against issuing create-cluster or join-cluster multiple times. It might be hard to recover in that case.
=> Validate create-cluster join-cluster APIs

core/api-server/socket/action.go
Some modules provide multiple log sources (subcomponents). E.g. Mail has distinct Postfix components with a "/suffix" qualifier:
- mail1
- mail1/anvil
- mail1/master
- mail1/submission/smtpd
This PR changes the Log page filter/match logic to include the "/suffix" notation for such modules.
See individual commit for details.
=> Log match for module subcomponents

core/install.sh
Catatonit could not be installed on a minimal installation (find in digital ocean), when we try to start a pod we have an error
```
systemd[58561]: Starting Loki pod service...
Aug 10 11:24:54 mattermost.nethserver.fr podman[58943]: Error: building local pause image: finding pause binary: exec: "catatonit": executable file not found in $PATH
```
we need to install catatonit to fix the issue
```
[root@mattermost ~]# rpm -qa catatonit podman
podman-4.1.1-6.el9.x86_64
catatonit-0.1.7-7.el9.x86_64
```
=> Catatonit must be installed to create pod

core/install.sh
```
[root@ns8loc ~]# curl https://raw.githubusercontent.com/NethServer/ns8-core/main/core/install.sh | bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  2559  100  2559    0     0   7849      0 --:--:-- --:--:-- --:--:--  7849
Restart journald:
Install dependencies:
CentOS Stream 9 - BaseOS                                                                              19 kB/s |  10 kB     00:00    
CentOS Stream 9 - BaseOS                                                                             2.2 MB/s | 5.9 MB     00:02    
CentOS Stream 9 - AppStream                                                                           17 kB/s |  11 kB     00:00    
CentOS Stream 9 - AppStream …
```
=> podman-catatonit conflicts catatonit

core/imageroot/usr/local/agent/actions/import-module/05create_volumes, core/imageroot/usr/local/agent/actions/import-module/10recvstate, core/imageroot/usr/local/agent/actions/import-module/validate-input.json
Volume names convention for rootfull modules wants the module ID as volume name prefix.
It is not possible to predict the module ID and use it to build correct volume names for rootfull modules.
This commit automatically adds the prefix for rootfull module volumes during the import-module action.
=> Import volumes for rootfull modules

core/imageroot/var/lib/nethserver/cluster/actions/list-domain-groups/50list_groups, core/imageroot/var/lib/nethserver/cluster/actions/list-domain-users/50list_users, core/imageroot/var/lib/nethserver/cluster/actions/list-user-domains/50read, core/imageroot/var/lib/nethserver/cluster/actions/list-user-domains/validate-output.json, core/imageroot/var/lib/nethserver/cluster/actions/remove-external-domain/50remove_domain, core/imageroot/var/lib/nethserver/cluster/actions/remove-internal-domain/50remove_domain, docs/core/database.md
Return the number of users and groups in the domain as cached from the last run of list-domain-groups/users.
=> Add counters to list-user-domains API

core/imageroot/usr/local/agent/pypkg/cluster/userdomains.py, core/imageroot/var/lib/nethserver/cluster/actions/list-user-domains/50read
Honor the same priority of domain records in both API (list-user-domains) and Ldapproxy output.
Domain names must be unique. This rule is enforced by the API validators.
However if validators are bypassed by modules there can be domains with the same name. This commit ensures the internal has higher priority over external.
=> Fix internal/external user domains priority

.devcontainer/Dockerfile, .devcontainer/base.Dockerfile, .devcontainer/devcontainer.json, core/ui/Containerfile, core/ui/README.md
There are two ways to develop NS8 UI from inside a container:
- build and start a Podman container (`core/ui/Containerfile`)
- use VS Code **Dev Containers** (`.devcontainer` directory)
This is explained in `core/ui/README.md`
=> Support UI development from inside a container

core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/remove-module/50update, docs/core/events.md
We could need for some modules like fail2ban or crowdsec to be advertized when a module is installed or removed. At the end of the installation or the removal the event is triggered, only module which have subscribed to the event will use them
=> Create events module-added and module-removed

core/build-image.sh
The upstream image has changed NodeJS version. This commit pins version 16.
error:0308010C:digital envelope routines::unsupported
=> Fix UI build error

core/imageroot/var/lib/nethserver/node/actions/remove-module/50update
When you remove a rootless module, we have to terminate (kill)  all sessions relevant to the user before to remove the module with its associated user.
=> Terminate the user session before to remove the module

core/imageroot/var/lib/nethserver/node/actions/remove-module/50update
When we remove a rootfull container, the volumes are not destroyed even if asked
We cannot inspect the containers because at this point the container has been probably removed by the destroy-module action of the container. 
The possibility I see is to state that the documentation asks the volume must be named by  "module_id-something", therefore we could find the volumes and remove them.
=> Find the rootfull volumes and remove them

.vscode/settings.json, core/build-image.sh, core/ui/.gitignore, core/ui/Containerfile, core/ui/README.md, core/ui/package.json
Set `NODE_OPTIONS=--openssl-legacy-provider` in container as environment variable.
**About development inside VS Code container**
it looks like VS Code is ignoring the specified Node version inside `devcontainer.json` and always uses Node v16.
Since Node v16 doesn't accept `NODE_OPTIONS=--openssl-legacy-provider`, we need to set this environment variable inside VS Code integrated terminal before launching `yarn` commands. This has been configured inside `.vscode/settings.json`
=> Use Node v18 (enhancements)

core/imageroot/var/lib/nethserver/cluster/actions/import-module/50import, core/imageroot/var/lib/nethserver/cluster/actions/import-module/validate-output.json
Return the waiting task ID to the caller, so it can synchronize with the worker module.
=> api. Return task ID for import-module

core/imageroot/usr/local/agent/actions/import-module/00validate_import, core/imageroot/usr/local/agent/actions/import-module/99mark_completed
After import-module completes, do not allow a new run of it. Fail with a validation error if this happens.
This should prevent errors from the ns7 migration tool to destroy a running module.
=> import-module. Run import-module one time

core/imageroot/var/lib/nethserver/node/install-core.sh, core/install.sh, core/tests/10__cluster_sanity/21__default_name.robot
Edited the install.sh script to export in environment the random name of the container used to unpack the core.
Setting the name for the node just created before the cluster creation / node join.
=> Added default cluster name on core installation

core/rsync/entrypoint.sh
For security reasons, the default behavior of rsyncd is adding an absolute and non-existing path to relative symlinks.
Switching off this behavior preserves the original symlink value. It is required by .dovecot.sieve symlinks in Mail module migration.
=> rsyncd. Keep symlinks in module state transfers

core/install.sh
Since release 9.1, Podman rootfull containers stopped to work on Rocky Linux due to SELinux issues. Even the install scripts hangs on Redis startup.
The installation succeedes on CentOS Stream though: https://github.com/NethServer/ns8-core/actions/runs/3567385345/jobs/5995025566
=> Fix for Rocky Linux 9.1

core/imageroot/var/lib/nethserver/node/actions/remove-module/50update
The command holds the lock on /etc/passwd and prevents other processes to modify it. Removing a big home directory holds the lock for a long time, blocking the removal of other modules.
=> Fix userdel home locking

docs/modules/service_providers.md
Add a small docs change that pushes using local Redis replica to discover other services setup.
See also https://github.com/NethServer/ns8-kickstart/pull/19
=> Connect local Redis replica for discovery

core/imageroot/var/lib/nethserver/node/install-core.sh
This PR allows rootless modules to add more Python packages to the base  `pyenv` agent environment: they are installed under the module home directory, with `pip install --user ...` 
References:
https://peps.python.org/pep-0405/#isolation-from-system-site-packages
> [PEP 370](https://peps.python.org/pep-0370) user-level site-packages are considered part of the system site-packages for venv purposes: they are not available from an isolated venv, but are available from an include-system-site-packages = true venv.
=> Allow addition of pip packages

core/imageroot/var/lib/nethserver/cluster/actions/restore-module/50restore_module
**Bug description**
In a disaster recovery, if I restore a module backup in a new cluster I expect the MODULE_UUID from the backup is applied, because the module UUID can be used by other modules to identify the right module instance and restore the relation between modules (e.g. Webtop - Mail).
**With the PR**
If a module backup is restored in a cluster with no instances of that module, or if there is not an instance with the same MODULE_UUID, the restore-module action is invoked with "replace=true", to preserve the original MODULE_UUID from backup.
The UI actually disables the Replace checkbox under the same conditions, preventing MODULE_UUID to be preserved.
**Effects of this change to other expectations**
If I want to use backup-restore as a path to migrate a module instance to a new …
=> Override replace flag for restore-module

core/agent/README.md, core/agent/agent.go, core/agent/envstate.go, core/agent/hevent.go, core/agent/htask.go, core/agent/test/actions/dump-environment/10setenv, core/agent/test/actions/dump-environment/20dumpenv, core/agent/test/actions/dump-environment/30failure, core/agent/test/suite/20__environment.robot, core/agent/test/suite/60__shutdown.robot, core/imageroot/usr/local/agent/pypkg/agent/__init__.py, docs/modules/agent.md
This PR changes the behavior of the module `agent`  service. The changes purpose is to allow a parent action to start a child action and share the module state as much as possible, controlling the `./environment` file contents with  `set-env` and `unset-env` commands.
1. The `environment` state file is saved in a backup copy at the beginning of the action. If the action aborts, the backup contents are written to the state file again.
1. The `environment` state file is read at the beginning of each step and is written at the end of each step, if this is successful.
1. The dump-env command is removed.
This change of behavior is expected to be **backward compatible**. Existing code now prints deprecation/warning messages but still produces equivalent results.
=> Drop agent dump-env command

core/imageroot/usr/local/agent/actions/create-module/10selfadm_role, core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update, docs/core/agents.md
Every module is authorized to run configure-module on itself. If this is undesirable, or if more actions are needed it is possible to modify the Redis SET key that defines the `selfadm` role:
module/{module_id}/roles/selfadm
See also the attached documentation.
=> add-module. Define the `selfadm` role implicitly

core/imageroot/usr/local/agent/actions/transfer-state/50sendstate
The file apitoken.cache must be excluded from transfer-state (if it exists). Otherwise the destination module will use the source module credentials to authenticate itself.
=> Fix clone-module auth error

core/agent/hevent.go, core/imageroot/etc/nethserver/agent.env, core/imageroot/usr/local/agent/pypkg/agent/__init__.py
This PR defines a new environment variable `REDIS_REPLICA_ADDRESS=127.0.0.1:6379` for agents. They listen to events on the local Redis replica.
Listening for events on the local Redis replica ensures events and data are consistent during service startup. Some startup scripts (e.g. defined as Systemd PreExecStart= commands), read configuration from Redis.
=> Listen for events on local Redis replica

core/imageroot/etc/nethserver/skel/.config/systemd/user/transfer-state.target.wants/agent.service, core/imageroot/etc/systemd/user/agent.service, core/imageroot/etc/systemd/user/transfer-state.target, core/imageroot/usr/local/agent/actions/transfer-state/01set_weight, core/imageroot/usr/local/agent/actions/transfer-state/10sendpayload, docs/core/clone_module.md
First step to transfer the heavy data, second step to ensure data
integrity.
During the last rsync transfer, services are stopped by isolating the
`transfer-state.target` Systemd unit.
Rsync filter rules are moved from `state/` to `etc/` directory
(`etc/state-filter-rules.rsync`).
=> Two-steps rsync in transfer-state action

core/imageroot/usr/local/agent/actions/clone-module/05replace, core/imageroot/usr/local/agent/actions/clone-module/10recvstate, core/imageroot/usr/local/agent/actions/clone-module/90finalize, core/imageroot/usr/local/agent/actions/clone-module/validate-input.json, core/imageroot/usr/local/agent/actions/transfer-state/10sendpayload, core/imageroot/var/lib/nethserver/cluster/actions/clone-module/50clone_module, docs/core/clone_module.md
The Redis environment copy may be stale. It is safer to transfer it with rsync.
Also, the destination environment is merged with the source environment automatically. Only missing variables are merged.
Finally, for rootless modules the services are automatically enabled and started as set by the source module.
=> clone-module. Safe environment transfer

core/ui/src/components/shell/AppDrawer.vue
Before this fix, adding or removing an app from favorites was not working if the user clicked the **Favorite** toggle below app icon (it was working only by clicking app icon or app name).
Other changes: make **Favorite** toggle label more legible
See also https://trello.com/c/VE4iiDnI/255-core-p1-ui-favorites-are-not-saved
=> ui: fix add/remove app from favorites

core/imageroot/usr/local/agent/pypkg/agent/ldapclient/rfc2307.py, core/ui/public/i18n/en/translation.json, core/ui/src/components/domains/DomainUsers.vue
https://trello.com/c/ubnCGEKb/323-core-p3-openldap-user-lock-unlock-implementation
Changes:
- ldap library: expose `locked` flag
- ui: enable `disable/enable` action for OpenLDAP
See also https://github.com/NethServer/ns8-openldap/pull/2
=> Lock unlock

core/imageroot/var/lib/nethserver/cluster/actions/remove-internal-provider/50remove_provider, core/imageroot/var/lib/nethserver/cluster/actions/remove-internal-provider/validate-input.json
When removing a Samba DC, first also select an existing instance as designated survivor.
Transfer to the survivor all [FSMO roles](https://wiki.samba.org/index.php/Transferring_and_Seizing_FSMO_Roles#Displaying_the_Current_FSMO_Role_Owners), then execute the `leave-domain`.
While not strictly needed, the address of the designates survivor is used by the demote action to make sure to find the right server.
https://trello.com/c/cuKDUqag/187-core-p1-samba-join-dc-admin-password-validator
Example:
```
api-cli run cluster/remove-internal-provider --data '{"module_id": "samba5", "adminuser": "Administrator", "adminpass": "Nethesis,1234", "designated_survivor": "dc2.domain2.it"}'
```
=> api: remove-internal-provider, support samba leave

core/imageroot/usr/local/agent/actions/transfer-state/10sendpayload
Backup timer can't be migrated.
Avoid errors like:
```
Failed to enable unit: Unit file backup1.timer does not exist.
```
See https://trello.com/c/UwVkhiRV/324-core-p2-clone-fails-if-a-backup-is-configured
=> api: transfer-state, skip backup timers

core/imageroot/var/lib/nethserver/cluster/actions/update-routes/50update, core/imageroot/var/lib/nethserver/cluster/actions/update-routes/validate-input.json, docs/core/database.md
As the only legitimate use case is adding the IP address of some cluster node to obtain Samba DC replication through the cluster VPN, the update-routes action do not accept CIDR network parameters any more.
=> Restrict additional VPN routes to IP addresses

core/imageroot/var/lib/nethserver/cluster/actions/remove-internal-provider/50remove_provider
acquire-fsmo requires admin credentials
Samba PR: https://github.com/NethServer/ns8-samba/pull/12
See also https://trello.com/c/f6u0mII7/327-core-p1-ui-for-samba-domain-removal
=> api: fix acquire-fsmo in remove-internal-provider

core/imageroot/var/lib/nethserver/cluster/actions/get-defaults/50read
Sometimes python can fail to correctly resolve local hostname. See also https://bugs.python.org/issue5004
=> get-config: make sure to return a valid hostname

core/ui/public/i18n/en/translation.json
Add i18n string for `set-route` validation error: `host_is_not_valid_not_localhost`
=> ui: i18n string for set-route validation error

core/ui/package.json, core/ui/public/i18n/en/translation.json, core/ui/src/components/domains/AddInternalProviderModal.vue, core/ui/src/components/domains/CreateDomainModal.vue, core/ui/src/components/shell/AppDrawer.vue, core/ui/src/views/DomainConfiguration.vue, core/ui/src/views/DomainUsersAndGroups.vue, core/ui/src/views/Domains.vue, core/ui/src/views/Nodes.vue, core/ui/yarn.lock
- Optionally enable file server capabilities when configuring a Samba account provider
- Show Samba file server instances inside the App drawer
Other changes:
- Add app category **Security**
- Update `@nethserver/ns8-ui-lib`
- Clean up code
=> Samba file server UI

core/ui/src/components/domains/AddInternalProviderModal.vue, core/ui/src/components/domains/CreateDomainModal.vue, core/ui/src/components/domains/DeleteSambaProviderModal.vue, core/ui/src/views/Domains.vue
Samba file server app might appear/disappear in the app drawer when installing/uninstalling a domain/provider
=> ui: reload app drawer when adding/removing samba

core/ui/README.md, docs/ui/core.md
Move UI developer documentation from `core/ui/README.md` to developer manual website
=> doc: move UI dev documentation to developer manual

core/imageroot/var/lib/nethserver/node/actions/get-node-status/20read
the psutil.disk_partitions gives back the overlayFs partition mounted to `var/lib/containers/storage/overlay`, this could mislead the user because for him it got one less partition 
see https://trello.com/c/KqN3iegZ/386-core-p3-repeated-disk-info
```
[root@R1-pve state]# cat /etc/fstab 
#
#
#
#
/dev/mapper/rl-root     /                       xfs     defaults        0 0
UUID=2376ce48-2235-45e3-9300-aa231a73b165 /boot                   xfs     defaults        0 0
/dev/mapper/rl-home     /home                   xfs     defaults        0 0
/dev/mapper/rl-swap     none                    swap    defaults        0 0
```
```
[root@R1-pve state]# df -h
Filesystem           Size  Used Avail Use% Mounted on
devtmpfs             4.0M     0  4.0M   0% /dev
tmpfs                3.8G  504K  3.8G   1% …
```
=> Hide the overlayFs partition in get-node-status

core/install.sh
https://trello.com/c/yRtB6t0I/376-core-p2-installer-add-checks
add test if 80 and 443 are not already in use
wget is a mandatory for debian
=> add more tests to NS8 installer

core/imageroot/usr/local/agent/pypkg/agent/__init__.py, docs/core/hostname.md, docs/modules/code_snippets.md
We could make a function to retrieve by the agent the FQDN of the server
The python library could fail even with socket.getfqdn, it is maybe better to use the bash command
to use it 
```
#!/usr/bin/env python3
import sys
import json
import agent
fqdn = agent.get_hostname()
json.dump(fqdn, fp=sys.stdout)
```
Add also the documentation of 
agent.tcp_port_in_use
agent.http_route_in_use
=> function to retrieve FQDN of server

core/imageroot/usr/local/agent/pypkg/cluster/modules.py
If metadata repository are not accessible, the logo must be always available
Card: https://trello.com/c/Kwu5FnOl/361-core-p2-app-drawer-icons-and-metadata
=> list-installed-modules: get icon from local disk

core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/50update
Change implementation to file backend
See also: https://github.com/NethServer/ns8-traefik/pull/38
Card: https://trello.com/c/Zc20ffWx/416-core-p1-traefik-dirs-backend-migration
=> create-cluster: set VPN network for traefik

core/ui/src/components/domains/AddInternalProviderModal.vue, core/ui/src/components/error/TaskErrorInfo.vue
Validate Samba IP address only if "Provide file shares and authentication to Windows clients" toggle is enabled
Trello card: https://trello.com/c/W5vw07Tl/410-core-p1-adding-samba-provider-dialog-unresponsive
Other changes:
- Improve task error visualization
=> UI: Fix add Samba provider validation

core/ui/package.json, core/ui/public/i18n/en/translation.json, core/ui/src/components/nodes/PromoteNodeModal.vue, core/ui/src/components/shell/AppDrawer.vue, core/ui/src/views/Nodes.vue, core/ui/yarn.lock
Get default value for VPN endpoint address from `get-info` action.
Trello card: https://trello.com/c/UMt11syd/409-core-p1-bad-endpoint-in-node-promotion-page
Other changes:
- App drawer: fix app logo alternate text
- Update `@nethserver/ns8-ui-lib`
=> UI: fix default vpn endpoint address on node promotion

core/ui/src/components/settings/Enable2FaModal.vue
Enable 2FA modal: fix a bug that refreshes the page when hitting <kbd>Enter</kbd> key on **6-digit code** input field
=> UI: fix enable 2FA modal

.github/workflows/build-disk-images.yml
Changes:
- keep only Rocky linux as RHEL variant
- do not create DigitalOcean snapshots (not used right now)
- upload to DO spaces to overcome 2GB size limit
- remove streamOptimized option which is not compatible with WMWare
NS8 on Rocky Linux 9:
* [QEMU/Proxmox (qcow2)](https://distfeed.nethserver.org/ns8-images/ns8-rocky-linux-9-ns8-stable.qcow2)
*  [VMWare (vmdk)](https://distfeed.nethserver.org/ns8-images/ns8-rocky-linux-9-ns8-stable.vmdk)
NS8 on Debian 12:
* [QEMU/Proxmox (qcow2)](https://distfeed.nethserver.org/ns8-images/ns8-debian-12-ns8-stable.qcow2)
* [VMWare (vmdk)](https://distfeed.nethserver.org/ns8-images/ns8-debian-12-ns8-stable.vmdk)
Card: https://trello.com/c/iLLGyoUh/372-core-p2-improve-pre-built-images
See also: https://github.com/NethServer/ns8-images/pull/4
=> image build: change targets and upload

core/ui/src/views/NodeDetail.vue, core/ui/src/views/Nodes.vue
Refreshing nodes data too often can be expensive; let's slow down refresh interval to 30 seconds.
=> UI: slow down refresh interval of nodes data

core/imageroot/usr/local/agent/actions/update-module/05pullimages, core/imageroot/usr/local/agent/actions/update-module/validate-input.json, core/imageroot/var/lib/nethserver/cluster/actions/update-module/50update, core/imageroot/var/lib/nethserver/cluster/actions/update-module/validate-input.json, docs/modules/updates.md
Force the module update even if the given `module_url` is already present in the local Podman storage
=> api. Add `force` flag to `update-module` action

core/ui/public/i18n/en/translation.json, core/ui/src/views/settings/SettingsTlsCertificates.vue
With the PR https://github.com/NethServer/ns8-traefik/pull/45 We list all obtained or requested LE certificate but these certificate cannot be removed from the UI when they have been obtained by set-route. You have to go to the module page and set to false the toggle button of lets_encrypt
This PR only disabled the trash button when the type === 'route'
See https://trello.com/c/WwdiFzRf/435-core-p0-list-of-certificates-is-incomplete
=> Hide delete button certificate for type route

core/imageroot/var/lib/nethserver/node/actions/set-fqdn/20set_fqdn
When we configure the hostname during the first connexion to `cluster-admin` we write the /etc/hosts accordingly but we do not write the relevant MOTD, it needs to wait a restart of the server or of the service api-server to rewrite it fully correctly
https://github.com/NethServer/dev/issues/6821
=> Write the MOTD when set hostname

core/ui/public/i18n/en/translation.json, core/ui/src/components/settings/CreateOrEditHttpRouteModal.vue, core/ui/src/components/settings/HttpRouteDetailModal.vue
This pull request adds a new option to the route creation process that allows skipping certificate validation for the backend target URL. This can be useful in cases where the target URL is using a self-signed or invalid certificate.
https://github.com/NethServer/dev/issues/6822
=> Add skip certificate validation option to route creation

core/ui/src/components/backup/RestoreMultipleInstancesSelector.vue
This pull request updates the instance display in the RestoreMultipleInstancesSelector.vue file. It changes the display from `instance.instance` to `instance.path`. This change improves the accuracy of the displayed information.
https://github.com/NethServer/dev/issues/6827
=> Update instance display in RestoreMultipleInstancesSelector.vue

core/ui/src/App.vue, core/ui/src/views/SoftwareCenter.vue
After updating core some errors may appear on the UI.
The cause is that API server is not be ready to receive request right after websocket reconnection and `update-core` completion.
- Retry websocket reconnection after 10 seconds instead of 5
- After `update-core` completion, wait 5 seconds before reloading data on the UI
Refs https://github.com/NethServer/dev/issues/6813
=> Fix failed requests in Software Center

core/ui/public/i18n/en/translation.json, core/ui/src/views/InitializeCluster.vue
This pull request updates the translation for the "domains" label to "external_domains" in the InitializeCluster.vue file. This change ensures consistency and clarity in the user interface.
The translation doesn't reflect the right name of `Domains` string, the [code ](https://github.com/NethServer/ns8-core/blob/main/core/imageroot/var/lib/nethserver/cluster/bin/cluster-backup#L68) is done to make a counter of external ldap user domain IIUC, this is explained in the [documentation](https://github.com/NethServer/ns8-core/blob/main/docs/core/database.md?plain=1#L251)
the documentation states 
`|cluster/user_domain/ldap/{domain}/conf                 |HASH   |An external LDAP domain|`
https://github.com/NethServer/dev/issues/6834
=> Update translation for "domains" to "external_domains"

core/ui/src/views/InitializeCluster.vue
Upload of backup file during cluster restore was broken on Windows clients: the detected MIME type is different from the one detected on Linux clients.
The retrieval of the base64 representation of the uploaded file now ignores its MIME type and works as expected.
Refs:
- https://github.com/NethServer/dev/issues/6832
=> Restore cluster: fix upload of backup file on Windows

core/ui/package.json, core/ui/src/components/domains/ChangeUserPasswordModal.vue, core/ui/src/components/domains/CreateOrEditUserModal.vue, core/ui/src/stories/NsPasswordInput.stories.js, core/ui/yarn.lock
This pull request adds the functionality 
to enforce a minimum length for passwords in the ChangeUserPasswordModal and CreateOrEditUserModal components. The minimum length is set to 8 characters.
to check the complexity of the password (upper, lower, digit and symbol)
- strength disabled
- strength enabled but complexity disabled
- strength enabled and complexity enabled
- validation 
https://github.com/NethServer/dev/issues/6845
=> Add minLength and checkComplexity password policy functionality

core/imageroot/var/lib/nethserver/cluster/actions/restore-cluster/30load
This pull request fixes an issue where the 'ui_names' were missing in the cluster restore process. The code now checks if 'ui_names' is present in the domain before setting it in the Redis database. This ensures that the 'ui_names' are properly restored during the cluster restore process.
https://github.com/NethServer/dev/issues/6855
=> Fix issue with missing 'ui_names' in cluster restore

core/imageroot/var/lib/nethserver/cluster/actions/bind-user-domains/50bind_user_domains
This pull request adds a domain inclusion check in the `bind-user-domains` script. The script now verifies if the `domain_list` is included in the list of domains before making any changes. If the `domain_list` is not included, an error message is printed and the script exits with an error code. This ensures that only valid domains are processed.
the error handled is 
```
Error: the domain_list ['rocky9-pve6.org'] is not included in the list of domains ['toto', 'domain', 'ad.rocky9-pve2.org', 'rocky9-pve2.org']
```
https://github.com/NethServer/dev/issues/6860
=> Add domain inclusion check in bind-user-domains script

core/imageroot/var/lib/nethserver/cluster/actions/add-external-domain/validate-input.json, core/ui/public/i18n/en/translation.json
This pull request adds hostname, IPv4, and IPv6 format validation for the TCP backend endpoint configuration. This ensures that the host field in the configuration accepts valid hostnames, IPv4 addresses, and IPv6 addresses.
https://github.com/NethServer/dev/issues/6856
=> Add hostname, IPv4, and IPv6 format validation for TCP backend endpoint configuration

core/imageroot/var/lib/nethserver/cluster/actions/add-external-domain/validate-input.json
This pull request fixes the format validation for the hostname field in the validate-input.json file. Previously, there was a trailing comma in the format validation, which has been removed in this commit.
https://github.com/NethServer/dev/issues/6856
=> Fix hostname trailing comma format validation in validate-input.json

core/ui/src/components/domains/DomainGroups.vue, core/ui/src/components/domains/DomainUsers.vue
This pull requests disables the deletion of the `administrator` user and the `domain admins` group
Ref: NethServer/dev#6863
=> Prevent deletion of administrators and domain admins group

core/ui/public/i18n/en/translation.json, core/ui/src/views/ClusterStatus.vue
This pull request add a line in the "Nodes" card in the "Cluster status" view to inform the user about the status of the nodes in the "Nodes" view.
Ref: NethServer/dev#6868
=> Add an information line on "Nodes" card about nodes status in "Cluster status" view

core/ui/src/views/SystemLogs.vue
This pull request add the name of the application's node inside the app selector in "System Logs" view, if the node has no name, we will display the node number
Ref: NethServer/dev#6870
=> Display node name or node number inside app selector in "System Logs" view

core/imageroot/usr/local/agent/actions/get-status/20read
This pull request refactors the service path handling for the systemd template and adds exclusion for services with names like "phpfpm@.service". This improves the efficiency and accuracy of the service filtering process.
systemed template appears but only the master template
instead I would like rootless
for rootfull container
https://github.com/NethServer/dev/issues/6892
=> Refactor service path handling for systemd template and exclude certain services

core/imageroot/var/lib/nethserver/node/actions/set-fqdn/30send_event, docs/core/events.md
This change is needed by NethServer/ns8-dnsmasq#3
Ref: NethServer/dev#6877
=> feat: added fqdn-changed event when setting fqdn

core/imageroot/usr/local/sbin/switch-leader, core/imageroot/var/lib/nethserver/node/events/default-instance-changed/10loki
On leader switch, install a new loki instance and notify the cluster of that change.
If `default-instance-changed` has a `instance` value of `loki`, reload promtail, automatically fetches the new `loki@cluster` module, and send logs to new instance.
Ref: NethServer/dev#6890
=> feat: adding loki instance on leader switch

core/imageroot/usr/local/agent/actions/transfer-state/10sendpayload
During clone testing a module, we've found that the core was still wanting to move systemd entries of rootful modules in contrast with what [documentation states](https://nethserver.github.io/ns8-core/core/clone_module/#implementation-of-transfer-state).
Ref: [Mattermost](https://mattermost.nethesis.it/nethesis/pl/x5rcozuuhffe8dzniqa8sgoq7o)
=> fix: avoid systemctl migration of rootful modules

core/api-moduled/README.md, core/api-moduled/api-moduled.go
`api-moduled` now supports Basic authentication via:
- `GET /api/auth`
```bash
curl -s 'https://<ip>/users-admin/<domain>/api/auth' -H 'Authorization: Basic base64(<username>:<password>)' -H 'content-type: application/json' | jq
curl -s 'https://<username>:<password>@<ip>/users-admin/<domain>/api/auth' -H 'content-type: application/json' | jq
```
=> auth. added new GET /api/auth for basic auth

core/ui/src/components/domains/CreateOrEditUserModal.vue
This pull request adds validation for the displayName field in the CreateOrEditUserModal component. If the displayName is not provided, an error message is displayed and the focus is set on the displayName input field. This change improves the user experience by ensuring that the required field is filled out before submitting the form.
https://github.com/NethServer/dev/issues/6930
=> Add validation for displayName in CreateOrEditUserModal

core/ui/src/components/nodes/SetFqdnModal.vue
This pull request updates the labels for the hostname and domain fields in the SetFqdnModal component. The labels were changed to "init.hostname_create" and "init.domain_create" respectively. This change improves the clarity and accuracy of the labels in the user interface.
https://github.com/NethServer/dev/issues/6927
=> Update SetFqdnModal labels for hostname and domain creation

core/ui/src/views/settings/SettingsSystemLogs.vue
This pull request remove a validation on core ui, to avoid incorrect error on loki instance label change.
Now it is possbile to reset loki instance label to empty.
[NethServer/dev#6929](https://github.com/NethServer/dev/issues/6929)
=> Removed loki instance label validation

core/ui/src/App.vue, core/ui/src/views/ClusterStatus.vue
This PR solves the following bug:
- https://github.com/NethServer/dev/issues/6967
Other changes:
- Fix a javascript error that appeared on the console while trying to invoke `get-support-session` on the leader node of an uninitialized cluster
=> Fix redirect to welcome page

core/ui/public/i18n/en/translation.json, core/ui/src/components/software-center/AppInfoModal.vue
- Remove "Source package" link from modal footer
- Show app source repository as the first element of "Images" list
=> fix: improve app images in app info modal

core/ui/src/views/ClusterStatus.vue, core/ui/src/views/SoftwareCenter.vue
Before this fix the software center notified the user about not only stable updates, but testing updates too. Now only stable updates are notified on the UI, as expected.
Ref:
- https://github.com/NethServer/dev/issues/6956
=> fix: testing updates management

core/imageroot/var/lib/nethserver/cluster/actions/restore-cluster/30load
The cluster restore script has been fixed to properly advertise LDAP provider changes. Previously, the script was not correctly publishing the changes, but now it uses a transaction pipeline to ensure that the changes are properly advertised. This fix ensures that any changes made to the LDAP provider setup are correctly communicated to the relevant components.
https://github.com/NethServer/dev/issues/7027
=> Fix cluster restore script to advertise LDAP provider changes

core/imageroot/usr/local/agent/pypkg/agent/__init__.py, core/imageroot/usr/local/agent/pypkg/node/ports_manager.py, core/imageroot/var/lib/nethserver/cluster/actions/clone-module/50clone_module, core/imageroot/var/lib/nethserver/cluster/actions/import-module/50import, core/imageroot/var/lib/nethserver/node/actions/allocate-ports/50allocate, core/imageroot/var/lib/nethserver/node/actions/allocate-ports/validate-input.json, core/imageroot/var/lib/nethserver/node/actions/deallocate-ports/validate-output.json, docs/modules/port_allocation.md
Improve existing allocate port method to ease the update of complex modules.
Issue referencec:
- NethServer/dev#6974
- NethServer/dev#7035
Tested with NethSecurity Controller update: https://github.com/NethServer/ns8-nethsecurity-controller/pull/44
=> Port allocation: allow to keep existing range 

core/imageroot/var/lib/nethserver/node/actions/remove-module/50update
The PR intends to remove a local image when we remove a module both in case the module is on a worker or a leader node
https://github.com/NethServer/dev/issues/7054
=> Remove the image in the worker node

core/imageroot/usr/local/agent/actions/update-module/95cleanup_images, core/imageroot/usr/local/agent/actions/update-module/96cleanup_core_images
This pull request adds a script that compares the Docker/Podman images defined in the environment file with the currently installed images in Podman.
The script retrieves the list of existing images and their versions, and then compares them with the versions specified in the environment file. If a Podman image has a version lower than the one specified in the environment file, it is automatically removed.
https://github.com/NethServer/dev/issues/7073
=> Compare and remove outdated  image versions

core/ui/src/components/settings/CloudLogManagerConfigureModal.vue, core/ui/src/components/software-center/AppList.vue, core/ui/src/views/InitializeCluster.vue, core/ui/src/views/Login.vue, core/ui/src/views/SoftwareCenterCoreApps.vue
Remove unnecessary (and potentially dangerous) `v-html` from CloudLogManagerConfigureModal template.
Other changes:
- Reduce max-width of initialize cluster page
- Reduce max-width of login form on large screens
- Format code
=> fix: remove v-html from CLM modal

core/ui/src/styles/_core.scss, core/ui/src/views/Login.vue
Resume max-width rule for form fields on large screens.
This rule was previously removed but had a negative effect on several pages.
Before this PR:
After this PR:
Other changes:
- Improve style of login form on large screens
=> style: resume max-width rule for form fields

core/imageroot/var/lib/nethserver/node/actions/start-support-session/51publish_event, core/imageroot/var/lib/nethserver/node/actions/stop-support-session/51publish_event
Introduce two new steps to handle the publishing of events for starting and stopping support sessions. The scripts retrieve necessary information such as node ID, session ID, and support user from environment variables and Redis.
They publish events to the Redis channel to notify about the support session status.
- Created `51publish_event` in `start-support-session` to publish `support-session-started` events.
- Created `51publish_event` in `stop-support-session` to  publish `support-session-stopped` events.
https://github.com/NethServer/dev/issues/7095
=> Add events for support session start/stop

core/imageroot/etc/systemd/system/phonehome.service, core/imageroot/usr/local/agent/pypkg/cluster/inventory.py, core/imageroot/var/lib/nethserver/cluster/actions/get-facts/50get, core/imageroot/var/lib/nethserver/cluster/bin/phonehome, core/imageroot/var/lib/nethserver/cluster/bin/print-phonehome, core/imageroot/var/lib/nethserver/cluster/bin/send-phonehome
Changes:
- add a new inventory.py library
- create a `print-phonehome` script that uses the inventory library and generate the JSON ready to be sent to phonehome server
- create a `send-phonehome` script to actually send data
New info added to the phonehome:
- subscription status
- installed applications
- number of admins
- number of admins with 2fa enabled
- smarthost status
- list of enabled repositories
NethServer/dev#7274
Example if `runagent print-phonehome  | jq .facts.modules`:
```json
[
{
"id": "traefik1",
"version": "2.2.5",
"name": "traefik",
"node": "1"
},
{
"id": "ldapproxy1",
"version": "1.1.0",
"name": "ldapproxy",
"node": "1"
},
{
"id": "loki1",
"version": "1.2.2",
"name": "loki",
"node": "1"
},
{
"id": "netdata1",
"version": "2.0.0",
"name": "netdata",
"node": "1"
},
{ …
```
=> feat(phonehome): add new info

core/ui/src/views/settings/SettingsSystemLogs.vue
Refactor the bindings for retention days and node label in the SettingsSystemLogs component to use the `lokiToEdit` object, improving data handling and consistency.
https://github.com/NethServer/dev/issues/7280
=> fix: update retention and label bindings in SettingsSystemLogs

docs/modules/metadata.md
Introduce functionality to set release note URLs for modules, enhancing documentation accessibility.
NethServer/dev#7243
=> feat(metadata): add relnotes_url to module metadata for release changelog

core/imageroot/usr/local/agent/pypkg/cluster/modules.py, core/imageroot/var/lib/nethserver/cluster/actions/list-modules/validate-output.json, core/imageroot/var/lib/nethserver/cluster/repodata-schema.json, core/ui/public/i18n/en/translation.json, core/ui/src/components/software-center/AppInfoModal.vue, core/ui/src/components/software-center/UpdateAppModal.vue, core/ui/src/views/SoftwareCenterAppInstances.vue, core/ui/src/views/SoftwareCenterCoreApps.vue
Introduce functionality to set release note URLs for modules sourced from GitHub repositories, enhancing the documentation accessibility for users.
https://github.com/NethServer/dev/issues/7243
```json
{
"name": "Mattermost",
"description": {
"en": "Mattermost is a secure Open Source chat for team collaboration.",
"it": "Mattermost è una chat Open Source sicura per la collaborazione in team."
},
"logo": "https://distfeed.nethserver.org/ns8/updates/mattermost/logo.png",
"screenshots": [
"https://distfeed.nethserver.org/ns8/updates/mattermost/screenshots/screen1.png"
],
"categories": [
"collaboration"
],
"authors": [
{
"name": "de Labrusse Stéphane",
"email": "stephdl@de-labrusse.fr"
}
],
"docs": {
"documentation_url": "https://docs.mattermost.com/",
"bug_url": …
```
=> feat(softwareCenter): add release note URLs for GitHub code repositories

core/imageroot/var/lib/nethserver/node/bin/node-monitor
Changes:
- do not raise swap:full:<node_id> alert if the swap is not configured
- add a new swap:notpresent:<node_id> alert if swap is not present
NethServer/dev#7163
Example on my.nethesis.it:
=> fix(node-monitor): add new swap alert

core/ui/src/components/domains/AddExternalProviderModal.vue, core/ui/src/views/DomainConfiguration.vue
Refine the domain configuration logic for internal Active Directory schemas and emit a reload event after adding an external provider.
https://github.com/NethServer/dev/issues/7315
=> fix(ldap): Update domain configuration and reload event

core/ui/src/components/domains/AddExternalProviderModal.vue
Reset form fields in the AddExternalProviderModal upon showing the modal and update the loading state after adding an external provider.
https://github.com/NethServer/dev/issues/7326
=> Reset form fields and update loading state in AddExternalProviderModal

core/imageroot/usr/local/sbin/switch-leader
Make sure the metrics instance on the new leader has the same configuration of the old leader
=> fix(metrics): switch-leader, restore metrics configuration

core/imageroot/var/lib/nethserver/cluster/events/backup-status-changed/10node_monitor
Avoid error like:
```
"failed to collect textfile data" collector=textfile file=backup.prom err="failed to open textfile data file
\"/host/run/node_exporter/backup.prom\": open /host/run/node_exporter/backup.prom: permission denied"
```
=> fix(node_exporter): make backup.prom readable

core/ui/public/i18n/en/translation.json, core/ui/src/components/settings/CreateOrEditHttpRouteModal.vue, core/ui/src/components/settings/HttpRouteDetailModal.vue, core/ui/src/views/settings/SettingsHttpRoutes.vue
Changes:
- manual routes: add list of allowed IPs inside edit and add modal
- automatic routes: change only the allowed IPs
- kebab menu: move the Edit action as first action (is likely the one that users will access more often)
- route list: show new tags, "automatic" for module-created rules, "access restricted" if IP allow list is set
NethServer/dev#7348
List:
Details with ip allow list:
Details no ip allow list:
Edit manual route:
Now automatic routes are editable, only the ip allow list is editable for automatic routes:
Validation error:
=> feat(ui): add ip_allowlist

core/imageroot/var/lib/nethserver/cluster/actions/list-domain-users/50list_users, core/ui/public/i18n/en/translation.json, core/ui/src/components/domains/CreateOrEditUserModal.vue, core/ui/src/components/domains/DomainUsers.vue
Main issue: NethServer/dev#7349
To work properly, the UI requires to use updated version of Samba e OpenLdap modules:
- https://github.com/NethServer/ns8-samba/pull/84
- https://github.com/NethServer/ns8-openldap/pull/56
User list:
Add user, with mail validation:
Edit user, mail field:
Install the custom core image:
```
curl https://raw.githubusercontent.com/NethServer/ns8-core/main/core/install.sh > install.sh 
bash install.sh ghcr.io/nethserver/core:user_expiration_ui
create-cluster rl1.leader.cluster0.gs.nethserver.net:55820 10.5.4.0/24 Nethesis,1234
```
Setup custom images for Samba and OpenLDAP:
```
redis-cli hset cluster/override/modules samba ghcr.io/nethserver/samba:cluster_ui
redis-cli hset cluster/override/modules openldap ghcr.io/nethserver/openldap:cluster_ui
```
=> Cluster user expiration and mail address UI

core/build-image.sh, core/imageroot/etc/systemd/system/promtail.service, core/imageroot/var/lib/nethserver/node/bin/generate-promtail-config
Promtail is now deprecated and will be EOL in one year.
This PR allows to test Loki 3.x with the new stack.
Minimize the changes by keeping all file named after promtail.
There are only 2 required changes:
- use the alloy container image
- create the configuration with the new alloy syntax
Tested by generating a converted config file:
```
cd /var/lib/nethserver/node/state/
podman run -ti --rm -v ./promtail:/etc/alloy docker.io/grafana/alloy:v1.8.0 convert --source-format=promtail --bypass-errors --output=/etc/alloy/promtail.alloy /etc/alloy/config.yml
```
To update the core:
```
api-cli run update-core --data '{"core_url":"ghcr.io/nethserver/core:alloy","nodes":[1], "force": true}
```
Ref: NethServer/dev#7401
=> fix(promtail): replace with alloy

core/ui/public/i18n/en/translation.json, core/ui/src/components/backup/RestoreSingleInstanceModal.vue
Implement logic to disable the option to replace existing applications for certain instances, specifically excluding 'loki' and other module with static ports.
https://github.com/user-attachments/assets/8df2a279-c96c-4ae3-b94d-8001466e313d
Refs: https://github.com/NethServer/dev/issues/7405 and https://github.com/NethServer/dev/issues/7396
=> feat(restoration): add list exclusion in  restoration replacement logic

core/api-server/methods/auth.go
This header could be used by downstream applications to grant access for users.
See Grafana as an example.
Required by: https://github.com/NethServer/ns8-metrics/pull/25
=> feat(api-server): add X-Auth-User header

core/ui/src/components/settings/LokiCard.vue
Refactor date formatting in the LokiCard component to utilize `Intl.DateTimeFormat` for improved localization based on the user's language settings.
when EN-US is used we use MM-DD-YY
when IT-IT or FR-FR is used we return DD-MM-YY
it seems english people are smart they use with EN-GB DD-MM-YY
https://github.com/NethServer/dev/issues/7453
https://github.com/user-attachments/assets/6f8b4b0b-55ac-4e7e-a375-01cbece6ea61
=> Update date formatting in LokiCard component

.devcontainer/devcontainer.json, core/ui/Containerfile, core/ui/public/i18n/en/translation.json, core/ui/src/mixins/notification.js, docs/ui/core.md, docs/ui/library.md, docs/ui/modules.md
- Add i18n string `software_center.source_package`: it is used by NS8 modules and was deleted by mistake
- Upgrade to Node 22
- Remove useless debug print
=> fix: add i18n string used by modules & upgrade node

core/ui/public/i18n/en/translation.json, core/ui/src/components/settings/CloudLogManagerConfigureModal.vue
Implement validation to ensure the address starts with "http://" or "https://", enhancing user input accuracy. Update translations to include an error message for invalid URLs.
NethServer/dev#7577
=> Add URL format validation for address in CloudLogManagerConfigureModal
