NethServer/ns8-core

- .github/workflows/core.yml
- .github/workflows/traefik.yml
- core/build-image.sh
- traefik/build-image.sh
The workflow builds and pushes the Core images if files get changed under the core/ directory.
See this build https://github.com/NethServer/ns8-scratchpad/runs/2612712030?check_suite_focus=true
Images are pushed using the branch name as tag, e.g. https://github.com/orgs/NethServer/packages/container/redis/2597686?tag=ga-workflow
> Add GitHub workflow for Core

- .github/workflows/promtail.yml
- core/imageroot/var/lib/nethserver/cluster/state/images-catalog.txt
- promtail/README.md
- promtail/build-image.sh
- promtail/imageroot/actions/configure-module/10validate
- promtail/imageroot/actions/configure-module/20unit_env
- promtail/imageroot/actions/configure-module/30start_service
- promtail/imageroot/actions/create-module/10pull_image
- promtail/imageroot/actions/create-module/20initialize
- promtail/imageroot/actions/destroy-module/50destroy
- promtail/imageroot/promtail.service
- promtail/imageroot/state/promtail.yaml
https://grafana.com/docs/loki/latest/clients/promtail/
> Add promtail module 

- core/install.sh
- doc/installation.md
Override the default image name for developers
> Define COREIMAGE env var for install.sh

- core/agent/README.md
- core/agent/action/action.go
- core/agent/agent.go
- core/agent/test.sh
- core/agent/test/05validation-failed
- core/agent/test/10setenv
- core/agent/test/20printenv
- core/agent/test/30validation-failed
- Add status definition: `running` `aborted` `validation-failed` `completed` `pending` 
- Smooth `progress` increments
- Agent commands for fine-grained step progress
> Implement action state progress

- core/agent/agent.go
- core/imageroot/usr/local/bin/extract-image
- core/imageroot/usr/local/bin/extract-ui
- core/imageroot/usr/local/nethserver/agent/python/agent/__init__.py
- core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
- core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
- core/imageroot/var/lib/nethserver/cluster/ui/apps/README.txt
- core/imageroot/var/lib/nethserver/node/actions/add-module/50update
- core/imageroot/var/lib/nethserver/node/actions/remove-module/50update
- dokuwiki/build-image.sh
- dokuwiki/ui/index.html
- ldapproxy/build-image.sh
- ldapproxy/ui/index.html
- mail/build-image.sh
- mail/ui/index.html
- nextcloud/build-image.sh
- nextcloud/ui/index.html
- promtail/build-image.sh
- promtail/ui/index.html
- samba/build-image.sh
- samba/ui/index.html
- traefik/build-image.sh
- traefik/ui/index.html
- The module image structure must provide two subdirs: `/ui` and `/imageroot`
- Default paths can be overridden with image labels: `org.nethserver/uiroot` and `org.nethserver/imageroot`.
> Extract static files for the admin UI 

- core/api-server/methods/tasks.go
We expect a JSON-encoded output data from the Task.
If the unmarshal fails, return the output data itself as a string.
> Return Task output in JSON format

- core/imageroot/usr/local/nethserver/agent/python/agent/__init__.py
- dokuwiki/imageroot/actions/configure-module/10validate
- dokuwiki/imageroot/actions/configure-module/20configure
- dokuwiki/imageroot/actions/create-module/10pull
- nextcloud/imageroot/actions/configure-module/10validate
- nextcloud/imageroot/actions/configure-module/20configure
- nextcloud/imageroot/actions/create-module/10pull
- traefik/imageroot/actions/create-module/10expandconfig
Use python when possible, add validation actions
Replaces #11
> Refactor Nextcloud and Dokuwiki

- core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
- core/imageroot/var/lib/nethserver/cluster/actions/join-cluster/50update
- Changes related to aafbba5316ea6fa45309826bc0e1e246931bbc8e
- Fix join-cluster regressions
> Tasks api path

- core/agent/action/action.go
- core/agent/agent.go
- core/api-server/methods/auth.go
- core/imageroot/usr/local/nethserver/agent/python/cluster/grants.py
- core/imageroot/usr/local/sbin/add-user
- core/imageroot/usr/local/sbin/create-cluster
- core/imageroot/usr/local/sbin/grant-actions
- core/imageroot/usr/local/sbin/remove-user
- core/imageroot/usr/local/sbin/revoke-actions
- core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
- core/imageroot/var/lib/nethserver/cluster/actions/add-user/50update
- core/imageroot/var/lib/nethserver/cluster/actions/alter-user/50update
- core/imageroot/var/lib/nethserver/cluster/actions/grant-actions/50update
- core/imageroot/var/lib/nethserver/cluster/actions/remove-user/50update
- core/imageroot/var/lib/nethserver/cluster/actions/revoke-actions/50update
- core/install.sh
- doc/installation.md
Add API and CLI helper commands for users & roles management.
Cluster APIs:
- grant-actions
- revoke-actions
- add-user
- remove-user
- alter-user
Commands:
- add-user
- remove-user
- grant-actions
- revoke-actions
> Users and roles APIs

- core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
- core/install.sh
Add the NODE_ID variable also to the cluster and node agent environment.
> Add NODE_ID var to cluster and node

- core/imageroot/var/lib/nethserver/cluster/actions/add-node/validate-input.json
- core/imageroot/var/lib/nethserver/cluster/actions/add-node/validate-output.json
- core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/validate-input.json
- core/imageroot/var/lib/nethserver/cluster/validator-definitions.json
Add  `ipv4-cidr` string pattern to the cluster validation library
> IPv4 CIDR validation pattern

- core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
- core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
- core/imageroot/var/lib/nethserver/cluster/actions/add-user/50update
- core/imageroot/var/lib/nethserver/cluster/actions/alter-user/50update
- core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/50update
- core/imageroot/var/lib/nethserver/cluster/actions/join-cluster/50update
- core/imageroot/var/lib/nethserver/cluster/actions/remove-module/50update
- core/imageroot/var/lib/nethserver/cluster/actions/remove-user/50update
Use the new agent.assert_exp() function: the builtin "assert" statement is designed for debug purposes.
> core. Python "assert" refactor

- core/imageroot/usr/local/bin/extract-image
- core/imageroot/usr/local/bin/extract-ui
- core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
- doc/new_module.md
- dokuwiki/build-image.sh
- ldapproxy/build-image.sh
- netdata/build-image.sh
- nextcloud/build-image.sh
- promtail/build-image.sh
- samba/build-image.sh
- traefik/build-image.sh
Change the image labels according to label recommendations:
- https://github.com/opencontainers/image-spec/blob/master/annotations.md#rules
- https://docs.docker.com/config/labels-custom-metadata/#key-format-recommendations
Remove the `org.nethserver/register_default_instance` label: always enforce the default instance registration at cluster and node levels.
> Refactor image labels

- core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
- samba/imageroot/actions/create-module/20initialize
- traefik/imageroot/actions/create-module/20systemd
> Random fixes for latest regressions

- .github/workflows/repomd.yml
Start a remote workflow:
https://github.com/NethServer/ns8-repomd/actions/workflows/repomd.yml
> build. Trigger repomd build

- core/agent/README.md
- core/agent/agent.go
- core/imageroot/usr/local/nethserver/agent/python/agent/__init__.py
- agent: Add unset-env command
- core: Add agent.unset_env() function
> agent: Add unset-env command

- core/install.sh
Make it work if the user does not read the first part of the output
> install: improve cut&paste command

- doc/details.md
> Updates to details.md

- ldapproxy/README.md
> ldapproxy: fix README

- doc/details.md
Documentation about:
- Core UI
- Modules UI
- UI library `@nethserver/ns8-ui-lib` (https://github.com/NethServer/ns8-ui-lib)
> UI documentation

- core/imageroot/usr/local/sbin/create-cluster
- core/install.sh
Allow login to the UI before cluster initialization.
> install: set default password

- core/imageroot/usr/local/nethserver/agent/python/cluster/modules.py
- core/imageroot/var/lib/nethserver/cluster/actions/add-favorite/50update
- core/imageroot/var/lib/nethserver/cluster/actions/add-favorite/validate-input.json
- core/imageroot/var/lib/nethserver/cluster/actions/add-favorite/validate-output.json
- core/imageroot/var/lib/nethserver/cluster/actions/list-favorites/50read
- core/imageroot/var/lib/nethserver/cluster/actions/list-favorites/validate-input.json
- core/imageroot/var/lib/nethserver/cluster/actions/list-favorites/validate-output.json
- core/imageroot/var/lib/nethserver/cluster/actions/list-installed-modules/validate-output.json
- core/imageroot/var/lib/nethserver/cluster/actions/remove-favorite/50update
- core/imageroot/var/lib/nethserver/cluster/actions/remove-favorite/validate-input.json
- core/imageroot/var/lib/nethserver/cluster/actions/remove-favorite/validate-output.json
- Add 3 new APIs for the UI:
- `add-favorite`
- `remove-favorite`
- `list-favorites`
- Improve `list-installed-modules` output by adding the `module` field
> Favorite APIs

- core/imageroot/usr/local/nethserver/agent/python/agent/__init__.py
Split on "=" can occur only one time
> Fix agent.read_envfile()

- core/build-image.sh
- dokuwiki/build-image.sh
Use Yarn instead of NPM in Core and Dokuwiki `build-image.sh`
> build. use yarn instead of npm

- .github/workflows/core.yml
- .github/workflows/dokuwiki.yaml
Initial implementation for Dokuwiki
> Build cache of yarn.lock dependencies

- core/install.sh
Debian 11 has already the correct configuration
> install.sh: remove code for Debian 10

- core/agent/agent.go
- Fix Golang programming errors (break vs continue statements!)
- Avoid log lines repetitions
> Fix agent validation-failed

- docs/details.md
> doc. update UI documentation

- core/api-server/methods/tasks.go
- core/api-server/redis/redis.go
- core/imageroot/usr/local/agent/bin/eventsgw
- core/imageroot/usr/local/agent/pypkg/agent/tasks/exceptions.py
- core/imageroot/usr/local/agent/pypkg/agent/tasks/redisclient.py
- core/imageroot/usr/local/agent/pypkg/agent/tasks/run.py
- core/imageroot/usr/local/agent/pypkg/cluster/grants.py
- core/imageroot/usr/local/bin/api-cli
- core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
Check the Redis client idle time to see if an agent exists and is alive before submitting the task for it. The goal is avoiding deadlocks.
With this PR the api-server implements two layers of checks
1. Authorization check: is the client authorized to invoke action A on agent X?
2. Idle time check (this PR): is agent X alive and ready?
Without check 2 and if a task is submitted to X the task might block forever.
> Check the client is alive before task submission

- core/imageroot/etc/nethserver/pythonreq.txt
- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
- core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
- core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/50update
Use the builtin package "ipaddress".
> Drop Python ipcalc dependency

- core/agent/agent.go
Ensure the output and error data has been copied to memory before starting the next action step.
Refs a66aaebf21d5fd1c956467645b2d62f6cdeac296
> Fix reading stdout and stderr from action steps

- core/imageroot/usr/local/agent/actions/create-module/05pullimages
- core/imageroot/usr/local/agent/actions/update-module/05pullimages
- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
- core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
- `agent.get_image_name_from_url()`: returns the image name from its URL
- Resume commit 746f861, overwritten by #95
> Implement agent.get_image_name_from_url()

- core/imageroot/etc/profile.d/api-cli.sh
- core/imageroot/usr/local/agent/pypkg/agent/tasks/exceptions.py
- core/imageroot/usr/local/agent/pypkg/agent/tasks/redisclient.py
- core/imageroot/usr/local/bin/api-cli
- core/imageroot/usr/local/sbin/add-module
- core/imageroot/usr/local/sbin/add-user
- core/imageroot/usr/local/sbin/create-cluster
- core/imageroot/usr/local/sbin/grant-actions
- core/imageroot/usr/local/sbin/join-cluster
- core/imageroot/usr/local/sbin/remove-module
- core/imageroot/usr/local/sbin/remove-user
- core/imageroot/usr/local/sbin/revoke-actions
- core/imageroot/usr/local/sbin/update-routes
- accept agent/action qualifier argument
- set "extra" task info in shell API wrappers
- handle known exceptions
- submit `null` by default
- Bash action name completion: `# api-cli run clu<TAB><TAB><TAB>...`
> :christmas_tree: Enhanced api-cli command syntax

- core/imageroot/var/lib/nethserver/cluster/actions/add-backup-repository/10validate
- core/imageroot/var/lib/nethserver/cluster/actions/add-backup-repository/50update
- core/imageroot/var/lib/nethserver/cluster/actions/add-backup-repository/validate-input.json
- core/imageroot/var/lib/nethserver/cluster/actions/add-backup-repository/validate-output.json
- core/imageroot/var/lib/nethserver/cluster/actions/add-backup/10validate
- core/imageroot/var/lib/nethserver/cluster/actions/add-backup/50add_backup
- core/imageroot/var/lib/nethserver/cluster/actions/add-backup/validate-input.json
- core/imageroot/var/lib/nethserver/cluster/actions/add-backup/validate-output.json
- core/imageroot/var/lib/nethserver/cluster/actions/list-backup-repositories/50list
- core/imageroot/var/lib/nethserver/cluster/actions/list-backup-repositories/validate-output.json
- core/imageroot/var/lib/nethserver/cluster/actions/list-backups/50list
- core/imageroot/var/lib/nethserver/cluster/actions/list-backups/validate-output.json
Refs https://github.com/NethServer/ns8-scratchpad/pull/137
- add-backup-repository
- list-backup-repositories
- add-backup
- list-backups
> Additional API definitions for backup

- core/build-image.sh
- core/imageroot/usr/local/agent/pypkg/agent/backup/__init__.py
- core/imageroot/var/lib/nethserver/cluster/actions/list-backups/50list
- core/imageroot/var/lib/nethserver/cluster/actions/list-backups/validate-output.json
Add backup status info:
- total size
- number of files
- start date
- end date
- success status
Also use a custom redis image.
> Backup status and restic image

- infra/README.md
> infra: fix README commands

- core/imageroot/usr/local/agent/bin/rclone-wrapper
- core/imageroot/var/lib/nethserver/cluster/actions/add-backup-repository/10validate
- core/imageroot/var/lib/nethserver/cluster/actions/alter-backup-repository/50update
- core/ui/package.json
- core/ui/public/i18n/language.json
- core/ui/src/components/backup/AddRepositoryModal.vue
- core/ui/src/components/backup/EditRepositoryModal.vue
- core/ui/src/components/backup/RestoreModal.vue
- core/ui/src/mixins/notification.js
- core/ui/src/stories/NsBackupCard.stories.js
- core/ui/src/stories/NsMenuItem.stories.js
- core/ui/src/views/Backup.vue
- core/ui/yarn.lock
- UI for `restore-module` action
- Enhance `add-backup-repository` and `alter-backup-repository` validation
> Backup UI: restore module

- core/tests/samba-sanity/30_install_samba.robot
> tests: basic checks forsamba module

- docs/modules/new_module.md
- refactor tutorial
- use kickstart repository as example
> doc: describe kickstart repository

- core/imageroot/var/lib/nethserver/cluster/actions/restore-module/50restore_module
> backup. Explain why a temp file is needed

- docs/faq.md
- docs/index.md
> doc: add FAQ

- docs/core/testing.md
Integrate testing documentation
> doc: move testing inside the doc

- docs/core/validation.md
- docs/modules/agent.md
JSON and custom validation description.
> doc: add validation

- docs/core/updates.md
- docs/modules/updates.md
> doc: document updates

- core/ui/package.json
- core/ui/public/i18n/language.json
- core/ui/src/components/AppDrawer.vue
- core/ui/src/components/AppList.vue
- core/ui/src/stories/NsIconMenu.stories.js
- core/ui/src/stories/NsInfoCard.stories.js
- core/ui/src/stories/NsMenuItem.stories.js
- core/ui/src/styles/_carbon-utils.scss
- core/ui/src/styles/_core.scss
- core/ui/src/views/About.vue
- core/ui/src/views/Backup.vue
- core/ui/src/views/DomainDetail.vue
- core/ui/src/views/Domains.vue
- core/ui/src/views/Nodes.vue
- core/ui/src/views/Settings.vue
- core/ui/src/views/SettingsSoftwareRepositories.vue
- core/ui/src/views/SoftwareCenter.vue
- core/ui/src/views/SoftwareCenterAppInstances.vue
- core/ui/yarn.lock
- Software center: **Reload software repositories** button invokes `clean-repositories-cache` action
- App drawer: do not show core modules
- Enhancements to `NsIconMenu` and `NsMenuItem`
- Minor style enhancements
> Clean repo cache UI

- docs/modules/metadata.md
- docs/modules/new_module.md
Describe metadata format and how to use it inside modules
> doc: add metadata

- docs/modules/rootless_rootfull.md
- Podman terminology introduction
- Code examples for EUID
- Volumes section
- systemctl --user
> Docs: more rootfull/rootless differences

- docs/core/backup_restore.md
> doc: add module-cleanup-state

- core/api-server/audit/audit.go
- core/api-server/go.mod
- core/api-server/go.sum
- core/api-server/main.go
- core/api-server/methods/audit.go
- core/api-server/methods/auth.go
- core/api-server/methods/tasks.go
- core/api-server/middleware/middleware.go
- core/api-server/redis/redis.go
- core/api-server/socket/action.go
- core/api-server/socket/socket.go
- core/build-image.sh
...and also rename package URL from "scratchpad" to "core"
> Golang 1.18+ for api-server

- core/imageroot/usr/local/agent/pypkg/cluster/modules.py
- core/imageroot/var/lib/nethserver/cluster/actions/list-core-modules/50read
- core/imageroot/var/lib/nethserver/cluster/actions/list-core-modules/validate-output.json
- core/imageroot/var/lib/nethserver/cluster/actions/list-modules/50read
Core and modules updates are now listed inside different API.
> api: refactor list-modules, add list-core-modules

- .github/workflows/core.yml
Make sure to push tags to ghcr.io
> core workflow: execute on tag

- core/imageroot/var/lib/nethserver/cluster/actions/update-module/50update
- core/imageroot/var/lib/nethserver/cluster/actions/update-module/validate-input.json
- core/imageroot/var/lib/nethserver/cluster/actions/update-modules/50update
- update-module: the API can handle the update by querying software repositories.
- update-modules: the API updates all non-core modules
> Improve update APIs

- core/imageroot/usr/local/agent/pypkg/cluster/modules.py
- core/tests/20__cluster_ui/10__create_cluster.robot
- core/tests/20__cluster_ui/30__domains.robot
- core/tests/20__cluster_ui/40__software_center.robot
- core/tests/20__cluster_ui/50__system_logs.robot
- core/tests/keywords.resource
- core/ui/package.json
- core/ui/src/components/backup/AddRepositoryModal.vue
- core/ui/src/components/backup/CreateBackupModal.vue
- core/ui/src/components/shell/NotificationDrawer.vue
- core/ui/src/mixins/notification.js
- core/ui/src/stories/NsToastNotification.stories.js
- core/ui/src/views/Backup.vue
- core/ui/src/views/SettingsCluster.vue
- core/ui/src/views/SoftwareCenterAppInstances.vue
- core/ui/yarn.lock
- Show **Abort** button only for `clone-module` tasks
- Show node UI label in **App instances** page
- Increase timeout for UI tests (useful on slow or congested networks)
- Add **Clone App** UI test
- Add **System logs** UI tests
- Minor UI fixes
> UI enhancements

- .github/workflows/tests.yml
See also: NethServer/ns8-github-actions#8
> workflows: use external workflow for run the tests

- docs/faq.md
- docs/migration.md
Brief migration description including Nextcloud.
> doc: add migration

- core/imageroot/usr/local/agent/actions/get-status/20read
The API was returning wrong information for rootfull modules.
The behavior for rootless modules is unchanged.
> get-status api: fix for rootfull modules

- core/ui/public/i18n/language.json
- core/ui/src/App.vue
- core/ui/src/components/error/TaskErrorModal.vue
- core/ui/src/components/settings/RequestTlsCertificateModal.vue
- core/ui/src/components/system-logs/LogSearch.vue
- core/ui/src/mixins/notification.js
- core/ui/src/store/index.js
- core/ui/src/views/SystemLogs.vue
- core/ui/src/views/settings/SettingsHttpRoutes.vue
- core/ui/src/views/settings/SettingsTlsCertificates.vue
- Show Traefik logs on `set-certificate` error
- TLS certificates: show **Pending** status during LE certificate verification
- Minor UI fixes
> UI: Traefik set-certificate UI

- core/imageroot/var/lib/nethserver/cluster/actions/create-cluster/60wgboot
- core/imageroot/var/lib/nethserver/node/uninstall.sh
It will be easier to display it for the UI
> firewall: create service for wireguard

- core/imageroot/var/lib/nethserver/node/actions/get-firewall-status/20read
- core/imageroot/var/lib/nethserver/node/actions/get-firewall-status/validate-output.json
- core/ui/package.json
- core/ui/public/i18n/language.json
- core/ui/src/router/index.js
- core/ui/src/views/NodeFirewall.vue
- core/ui/src/views/Nodes.vue
- core/ui/yarn.lock
- `get-firewall-status` node action
- UI: show interfaces, services and ports on public zone
> api & ui: get-firewall-status

- core/imageroot/var/lib/nethserver/node/actions/get-firewall-status/20read
- core/ui/public/i18n/language.json
- core/ui/src/components/settings/RequestTlsCertificateModal.vue
- core/ui/src/views/NodeFirewall.vue
- Node firewall: fix network interfaces retrieval
- TLS certificates: minor fix
> UI: fixes to firewall and TLS certificates

- docs/quickstart.md
- More hardware support is likely to be added to the core in the future
- Modules have to be developed for multi-arches too
Ref https://community.nethserver.org/t/i-cant-install-ns8-on-hyper-v-in-windows-11-arm64/20439
> Add to docs quickstart x86_64 architecture core support

- core/api-server/methods/auth.go
- core/api-server/middleware/middleware.go
- core/imageroot/var/lib/nethserver/node/install-core.sh
When the user logs out, his token is removed from the list of valid tokens.
> core. api-server: remove token on logout response

- core/imageroot/usr/local/agent/actions/list-service-providers/10list_service_providers
- core/imageroot/usr/local/agent/actions/list-service-providers/validate-input.json
- core/imageroot/usr/local/agent/actions/list-service-providers/validate-output.json
- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
- docs/core/database.md
- docs/modules/agent.md
- docs/modules/service_providers.md
- Implementation of the basic action `list-service-providers`. It's inherited by every module.
- Add documentation page for modules that want to provide services for other modules.
> Base action list-service-providers

- core/ui/src/router/index.js
- core/ui/src/views/settings/SettingsSmartHost.vue
Fix the broken router from https://github.com/NethServer/ns8-core/pull/277
> Fix router broken build

- docs/core/smarthost.md
> Documentation for smarthost.py

- core/imageroot/usr/local/agent/actions/destroy-module/95cleanup_images
- core/imageroot/var/lib/nethserver/cluster/actions/remove-module/50update
- core/tests/10__cluster_sanity/60__clone_module.robot
Remove rootfull module additional images, too.
See also #273
> Clean-up module image on removal

- core/ui/package.json
- core/ui/src/stories/NsByteSlider.stories.js
- core/ui/src/stories/NsSlider.stories.js
- core/ui/src/styles/_core.scss
- core/ui/yarn.lock
Update `NsSlider` and `NsByteSlider` stories
> UI: update stories

- core/ui/package.json
- core/ui/src/stories/NsComboBox.stories.js
- core/ui/src/stories/NsMultiSelect.stories.js
- core/ui/src/styles/_core.scss
- core/ui/yarn.lock
Update storybook for new prop `showItemDescription`.
Other changes:
- Style fix for page subtitles
> UI: update NsMultiSelect & NsComboBox stories

- docs/best_pratices.md
Document how to add more space
> doc: add best practices

- core/imageroot/usr/local/agent/pypkg/cluster/modules.py
- core/imageroot/var/lib/nethserver/cluster/actions/update-modules/50update
Do not abort the whole API call when a subtask fails.
> Fix update-modules API

- core/ui/package.json
- core/ui/public/config/config.development.js
- core/ui/public/i18n/language.json
- core/ui/src/styles/_core.scss
- core/ui/src/views/DomainUsersAndGroups.vue
- core/ui/src/views/Domains.vue
- core/ui/src/views/SoftwareCenter.vue
- core/ui/yarn.lock
- **Domains and users** page: show users and groups counters
- **Domain users and groups** page: show users and groups in different tab views
> UI: users and groups enhancements

- core/install.sh
- docs/quickstart.md
Any RHEL 9 clone should work, however we write in the docs that we support what has been tested.
> Support Rocky Linux 9

- core/api-server/README.md
- core/api-server/api-server-logs.go
- core/api-server/models/socket.go
- core/api-server/socket/action.go
- core/ui/public/i18n/language.json
- core/ui/src/components/system-logs/LogSearch.vue
- core/ui/src/views/SystemLogs.vue
https://trello.com/c/vfKe3bfH/213-log-page-vs-timezone
> core. api-server & ui: added timezone in logs page

- core/imageroot/var/lib/nethserver/cluster/actions/remove-node/00validate_inuse
- core/imageroot/var/lib/nethserver/cluster/actions/remove-node/50remove_node
- core/imageroot/var/lib/nethserver/cluster/actions/remove-node/validate-input.json
Remove the given node from the cluster. No applications nor account providers can be running/installed on it.
> Add cluster/remove-node API action

- .devcontainer/devcontainer.json
- core/ui/Containerfile
- core/ui/README.md
- core/ui/container-entrypoint.sh
- hot-reload support
- support for production build
- update README
> Enhance UI development from inside a container

- .devcontainer/devcontainer.json
- core/build-image.sh
- core/ui/Containerfile
- core/ui/README.md
- core/ui/package.json
Other changes:
- Update `core/ui/README.md`
> Use Node v18

- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
http_route_in_use : Test if an url exists with the traefik api, return true is used or false
tcp_port_exists: Test if the port is used or not, return true is used or false
```
import agent
domain = agent.http_route_in_use(domain='rocky9-2.local', path='', expectation=404)
webpath = agent.http_route_in_use(domain='127.0.0.1', path='/foo', expectation=404)
port=agent.tcp_port_in_use(5555)
```
> Agent function http_route_in_use and tcp_port_in_use

- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
- core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
- core/imageroot/var/lib/nethserver/node/actions/add-custom-zone/50add
- core/imageroot/var/lib/nethserver/node/actions/add-custom-zone/validate-input.json
- core/imageroot/var/lib/nethserver/node/actions/remove-custom-zone/50remove
- core/imageroot/var/lib/nethserver/node/actions/remove-custom-zone/validate-input.json
- core/imageroot/var/lib/nethserver/node/install-core.sh
Add and remove custom firewall zones.
Required by https://github.com/NethServer/ns8-nextsec-controller/pull/3
> Custom firewall zones

- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
- docs/modules/service_providers.md
Added qualifier to list\_service\_providers, providing additional filtering.
Updated documentation.
> Improvements to Service Provider discovery

- core/build-image.sh
Due to issues with static building in `alpine`, I've tried to fix the problem due to the `musl` linker missing from the final executable.
These two options were considered, but they utterly were failures:
- :x: trying to add the official alpine package `build-base` still makes `go build` use `musl` as linker, so no success was reached.
- :x: dynamically building the executable is faster but introduces all sorts of the dependency issues, since the binary is not used inside a container.
A workaround for the soulution is to static build the executable inside the `bullseye` flavor of the `golang` container.
During building/running, no warning is provided due to missing libraries, `ldd` output seems fine.
> Fix Static Build

- core/ui/public/i18n/en.json
> UI: improve labels

- core/ui/src/components/domains/AddInternalProviderModal.vue
- core/ui/src/components/domains/DeleteSambaProviderModal.vue
- core/ui/src/views/DomainConfiguration.vue
**Domains and users**: user needs to enter Samba admin username and password in order to delete a Samba provider
**Other changes**: minor UI enhancements to `AddInternalProviderModal`
> UI: Enter Samba credentials to remove provider

- core/imageroot/var/lib/nethserver/node/actions/update-core/50update
The core may add some python libraries on updates.
https://trello.com/c/LdYSlLDM/335-core-p0-core-update-does-not-update-pip-requirements
Tested with: #368
> core update: install python requirements

- core/api-server/README.md
- core/api-server/api-server.go
- core/api-server/methods/auth.go
https://trello.com/c/0IR8erBO/338-core-p1-http-basic-auth-endpoint
> core. api-server: added basic_auth for modules

- core/ui/package.json
- core/ui/src/stories/NsInfoCard.stories.js
- core/ui/yarn.lock
- Update `NsInfoCard` storybook (improved title tooltip)
- Update `@nethserver/ns8-ui-lib`
See: https://github.com/NethServer/ns8-ui-lib/pull/22
> UI: Update NsInfoCard storybook

- core/ui/public/i18n/en/translation.json
- core/ui/src/components/software-center/AppList.vue
- core/ui/src/mixins/notification.js
- core/ui/src/views/Backup.vue
- core/ui/src/views/Nodes.vue
- core/ui/src/views/SoftwareCenter.vue
- core/ui/src/views/SoftwareCenterAppInstances.vue
- core/ui/src/views/settings/SettingsHttpRoutes.vue
- Improve some button labels and icons
- Minor UI enhancements
> Software center improvements

- core/imageroot/usr/local/sbin/apply-vpn-routes
- core/imageroot/var/lib/nethserver/cluster/actions/remove-node/00validate_inuse
- core/imageroot/var/lib/nethserver/cluster/actions/remove-node/50remove_node
- core/ui/public/i18n/en/translation.json
- core/ui/src/components/nodes/RemoveNodeModal.vue
- core/ui/src/mixins/node.js
- Show apps installed on node before node removal
- Reload app drawer after node removal
- Clean up Redis while removing node
See also: https://github.com/NethServer/ns8-core/pull/376
> Allow removal of node with apps installed on it

- core/imageroot/usr/local/sbin/switch-leader
- core/imageroot/var/lib/nethserver/cluster/actions/promote-node/10promote_node
- core/imageroot/var/lib/nethserver/cluster/actions/promote-node/validate-input.json
- core/imageroot/var/lib/nethserver/node/events/leader-changed/10switch_leader
- core/ui/public/i18n/en/translation.json
- core/ui/src/components/nodes/NewLeaderModal.vue
- core/ui/src/components/nodes/PromoteNodeModal.vue
- core/ui/src/components/nodes/RemoveNodeModal.vue
- core/ui/src/views/Nodes.vue
- core/ui/src/views/SoftwareCenterAppInstances.vue
- docs/core/events.md
- docs/core/vpn.md
Replaces https://github.com/NethServer/ns8-core/pull/378
**Nodes** page: promote node as leader role
Other changes:
- **App instances page**: show latest version available for upgradable apps
- Minor improvements
> Promote node to leader

- docs/_config.yml
- docs/design.md
- docs/development_process.md
- docs/index.md
https://trello.com/c/60oH89Ez/353-release-b1
> doc: add dev process

- CONTRIBUTING
- README.md
- Add CONTRIBUTING guidelines
- Change README for the repo (not strictly the whole NS8 project)
[skip ci]
> Fix core repo README

- docs/ui/core.md
> docs: UI dev minor improvements

- core/ui/package.json
- core/ui/public/i18n/en/translation.json
- core/ui/src/components/settings/UploadTlsCertificateModal.vue
- core/ui/src/views/settings/SettingsTlsCertificates.vue
- core/ui/yarn.lock
Added ui to allow upload of custom certificate
Merge after NethServer/ns8-traefik#33
Uploaded certificates won't come up due to [this bug](https://trello.com/c/pqBzeLC2/391-core-p-cannot-show-custom-certificates-in-ui), need to be browsed manually in `/home/traefikX/.config/state/certificates_custom`
> Upload custom certificate

- core/ui/public/i18n/en/translation.json
- core/ui/src/components/software-center/AppInfoModal.vue
Card: https://trello.com/c/qeHkMa6U/362-core-p3-display-more-app-metadata
> ui software center: more info on app page

- core/ui/package.json
- core/ui/public/i18n/en/translation.json
- core/ui/src/components/error/TaskErrorInfo.vue
- core/ui/src/components/error/TaskErrorInfoHierarchy.vue
- core/ui/src/components/error/TaskErrorModal.vue
- core/ui/src/components/error/TaskTreeHierarchy.vue
- core/ui/yarn.lock
Card https://trello.com/c/P3q1YcMu/369-core-p3-show-formatted-error-messages-on-task-error-modal
> ui: better error visualization

- core/imageroot/usr/local/agent/bin/cluster-backup
- core/imageroot/var/lib/nethserver/cluster/actions/restore-cluster/30load
- core/imageroot/var/lib/nethserver/cluster/actions/retrieve-cluster-backup/20save
- core/ui/public/i18n/en/translation.json
- core/ui/src/views/Backup.vue
- core/ui/src/views/InitializeCluster.vue
See https://github.com/NethServer/ns8-traefik/pull/39
Card: https://trello.com/c/NO3av3Gd/423-core-p2-back-and-restore-traefik-with-cluster
Show traefik info inside cluster restore summary:
Block backup button during dump creation:
> Traefik: move backup and restore inside cluster

- .devcontainer/devcontainer.json
- core/ui/public/index.html
- core/ui/src/App.vue
Show a spinner instead of a white page while loading Vue app
Other changes:
- Change devcontainer name
- Print ASCII art message on console on page load
> UI: show spinner while loading Vue app

- core/api-server/configuration/configuration.go
- core/api-server/go.mod
- core/api-server/go.sum
- core/api-server/methods/tasks.go
https://trello.com/c/CDUXhojm/406-core-p3-restrict-access-to-task-input-output
> core. api-server: obscure sensitive data in audit log

- .devcontainer/devcontainer.json
- core/ui/public/shortcuts.json
- core/ui/src/components/shell/GlobalSearch.vue
- Add results to global search
- Improve style of global search
Other changes:
- Build: add extensions to devcontainer
> UI: add results to global search

- .devcontainer/devcontainer.json
- core/ui/public/i18n/en/translation.json
- core/ui/src/components/nodes/NodeCard.vue
- core/ui/src/mixins/notification.js
- core/ui/src/styles/_core.scss
- core/ui/src/views/NodeDetail.vue
- docs/ui/core.md
- docs/ui/library.md
- docs/ui/modules.md
- Refactor library and modules documentation
- Fix and format code
Other changes:
- Nodes: if a node has more than two disks, show only the first two and a link "Show all disks"
- Node detail: show multi-core information more concisely
- Print task progress on dev console at debug level (hidden by default)
- Add extensions to vscode container
> Update documentation & other improvements

- core/imageroot/etc/systemd/system/phonehome.service
- core/imageroot/usr/local/bin/phonehome
https://trello.com/c/dHbAhUA3/370-core-p3-phonehome-shebang
> phonehome modify shebang to runagent env

- core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
- core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
- core/imageroot/var/lib/nethserver/node/install-finalize.sh
- docs/core/database.md
- docs/modules/agent.md
- docs/modules/network.md
- docs/modules/port_allocation.md
https://trello.com/c/X7VQ1lEb/424-core-p2-udp-port-allocation
> Allocate UDP port ranges

- core/imageroot/etc/systemd/system/tun-manager@.service
- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
- core/imageroot/usr/local/sbin/tun-manager
- core/imageroot/var/lib/nethserver/cluster/actions/add-node/50update
- core/imageroot/var/lib/nethserver/node/actions/add-tun/50add
- core/imageroot/var/lib/nethserver/node/actions/add-tun/validate-input.json
- core/imageroot/var/lib/nethserver/node/actions/remove-tun/50remove
- core/imageroot/var/lib/nethserver/node/actions/remove-tun/validate-input.json
- core/imageroot/var/lib/nethserver/node/install-finalize.sh
- docs/core/tun.md
Manage tun devices for rootless VPNs
See also:
- https://github.com/NethServer/ns8-nethsecurity-controller/pull/11
> Add tun-manager

- core/ui/public/i18n/en/translation.json
- core/ui/src/components/backup/AddRepositoryModal.vue
We need to specify differently how to retrieve the correct property to fix the focus when a field is not validated correctly by the Json schema
> Backup Handle error focus for properties

- core/imageroot/usr/local/agent/pypkg/cluster/modules.py
we miss to import sys to write to stderr 
Imported in https://github.com/NethServer/ns8-core/pull/522
> Fix missing sys in function

- docs/modules/agent.md
- docs/modules/automatic_builds.md
- docs/modules/systemd_units.md
The dev documentation was not updated on  link to dokuwiki module
> Update dokuwiki on configuration and automatic builds

- core/ui/src/views/DomainConfiguration.vue
This pull request refactors the password policy UI in the DomainConfiguration.vue file. The password policy and user portal are displayed only for internal user domain
https://github.com/NethServer/dev/issues/6794
> Refactor password policy UI in DomainConfiguration.vue

- core/ui/src/views/settings/SettingsSubscription.vue
This pull request includes two commits. The first commit refactors the cluster subscription description in SettingsSubscription.vue file. The second commit updates the subscription URLs in the translation.json file. These changes improve the clarity and functionality of the subscription management feature.
We want to prevent the use of v-html wit XSS vulnerabilities
https://github.com/NethServer/dev/issues/6815
> Refactor cluster subscription description and update subscription URLs

- core/ui/package.json
- core/ui/yarn.lock
Update @nethserver/ns8-ui-lib
See: https://github.com/NethServer/ns8-ui-lib/pull/28
> chore: update ns8-ui-lib to fix multiselect

- core/ui/public/i18n/en/translation.json
the trailing comma has broken cluster-admin
https://github.com/NethServer/dev/issues/6856
> fix broken translation

- docs/modules/code_snippets.md
- docs/modules/new_module.md
- docs/ui/core.md
- docs/ui/modules.md
Describe how to install extra python libraries inside the module environment.
> doc: document pip usage

- core/api-server/api-server-logs.go
- core/api-server/models/socket.go
- core/api-server/socket/action.go
- core/imageroot/usr/local/bin/logcli
- core/imageroot/var/lib/nethserver/cluster/actions/list-loki-instances/10get
- core/imageroot/var/lib/nethserver/cluster/actions/list-loki-instances/validate-output.json
Prerequisites:
- NethServer/ns8-core#615
- NethServer/ns8-loki#5
Ref: NethServer/dev#6890
> feat: add loki apis to core

- core/ui/src/components/nodes/SetFqdnModal.vue
https://github.com/NethServer/dev/issues/6943
> fix: fix node id when setting fqdn to a node

- core/imageroot/var/lib/nethserver/cluster/actions/list-loki-instances/10get
- core/imageroot/var/lib/nethserver/cluster/actions/list-loki-instances/validate-output.json
- core/ui/public/i18n/en/translation.json
- core/ui/src/components/settings/CloudLogManagerConfigureModal.vue
- core/ui/src/components/settings/LokiCard.vue
- core/ui/src/components/settings/SyslogConfigureModal.vue
- core/ui/src/styles/_core.scss
- core/ui/src/views/ClusterStatus.vue
- core/ui/src/views/InitializeCluster.vue
- core/ui/src/views/settings/SettingsSystemLogs.vue
UI parts:
- New modals on active loki cards
- New card on cluster status
- Some other fix
Actions:
- Added cloud log manager and syslog info to `list-loki-istances` api
[NethServer/dev#6932](https://github.com/NethServer/dev/issues/6932)
> Cloud Log Manager and Syslog forwarders

- core/ui/public/i18n/en/translation.json
- core/ui/src/components/error/TaskErrorModal.vue
- core/ui/src/components/shell/ShellHeader.vue
- core/ui/src/views/Nodes.vue
Remove unused tooltip hints from the UI
> fix: remove tooltip hints

- core/ui/package.json
- core/ui/public/i18n/en/translation.json
- core/ui/src/components/shell/NotificationDrawer.vue
- core/ui/src/components/shell/ShellHeader.vue
- core/ui/src/mixins/notification.js
- core/ui/src/views/ClusterStatus.vue
- core/ui/src/views/NodeDetail.vue
- core/ui/yarn.lock
Remove read state for notifications.
See:
- https://github.com/NethServer/dev/issues/6975
Other changes:
- Improve ongoing tasks loader in shell header
- Print tasks result in console at verbose level instead of log
- Fix Nodes card style in Cluster status page
- Format code
> fix: notifications enhancements

- core/ui/src/views/SoftwareCenterCoreApps.vue
The pull request fixes an issue where the incorrect function was being used to load the core module. The changes ensure that the correct function is used, resolving the issue.
https://github.com/NethServer/dev/issues/6991
> Fix loading of core module

- core/ui/src/components/backup/AddRepositoryModal.vue
- core/ui/src/components/domains/CreateOrEditUserModal.vue
- core/ui/src/views/settings/SettingsSmartHost.vue
Ref:
- https://github.com/NethServer/dev/issues/7065
> fix: disable autocomplete on various input fields

- core/imageroot/usr/local/agent/bin/module-backup
Enhance the backup process by improving error handling and providing detailed status reporting, including error counts and backup statistics.
https://github.com/NethServer/dev/issues/7093
> Improve error handling and status reporting in backup process

- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
Ref:
- https://github.com/NethServer/dev/issues/7207
> fix: hide allocate-ports notification

- core/ui/src/views/SoftwareCenterAppInstances.vue
Fix layout of **Update all instances** and **Install new instance** buttons in app instances page
> fix(ui): fix style of update & install app buttons

- core/ui/src/components/software-center/AppList.vue
- core/ui/src/router/index.js
- core/ui/src/views/SoftwareCenter.vue
- core/ui/src/views/SoftwareCenterCoreApps.vue
Save a click to install core updates
Other changes:
- Fix router path of **Core apps** page
- Simplify logic of update core timeout
Ref:
- https://github.com/NethServer/dev/issues/7227
> fix(ui): save a click to install core updates

- core/imageroot/usr/local/agent/pypkg/cluster/inventory.py
- core/imageroot/var/lib/nethserver/cluster/actions/get-facts/50get
Example:
```json
{
"subscription": "disabled",
"admins": {
"count": 1,
"2fa": 0
},
"repositories": [
"default"
],
"smarthost": {
"enabled": false,
"manual_configuration": true
},
"backup": {
"backup_count": 1,
"destination_count": 1,
"destination_providers": [
"backblaze"
]
}
}
```
> feat(phonehome): add backup fact

- core/imageroot/usr/local/agent/pypkg/agent/ldapclient/ad.py
- core/imageroot/var/lib/nethserver/cluster/bin/notify-password-warning
Changes:
- correctly check Samba expiration
- send all notifications (fix variable override)
> fix(password-warning): multiple fixes

- core/ui/.gitignore
- docs/ui/library.md
Update dev manual of NS8 UI library according to the following changes:
- Make build standard
- Add SBOM generation
Ref:
- https://github.com/NethServer/ns8-ui-lib/commit/5adc23118d9b66a3a2adc3995f4f737c2eb9928b
> docs: update NS8 UI library dev manual

- core/imageroot/usr/local/agent/pypkg/agent/__init__.py
- core/ui/src/views/settings/SettingsSmartHost.vue
Improve event handling for smarthost tasks by introducing unique event IDs and displaying notifications for task events.
https://github.com/NethServer/dev/issues/7377
https://github.com/user-attachments/assets/f2b57503-9a07-4b51-8fb3-bd7e7a4c4bd6
> feat(settings): show notifications for smarthost task events

- core/ui/src/components/backup/InstanceToRestoreInfo.vue
- core/ui/src/components/backup/RestoreSingleInstanceSnapshotSelector.vue
Refactor date formatting in components to use `Intl.DateTimeFormat` for better localization support. This change enhances the display of timestamps in the user interface.
https://github.com/NethServer/dev/issues/7453
https://github.com/user-attachments/assets/472af0e4-5f20-4111-8812-f9597f1108a4
> Replace inline date formatting with Intl.DateTimeFormat

- docs/core/phone_home.md
The old comment does not print all sent info
> fix(doc): phonehome, document new comment

- core/ui/public/i18n/en/translation.json
- core/ui/src/components/settings/CreateOrEditHttpRouteModal.vue
- core/ui/src/components/settings/RequestTlsCertificateModal.vue
- core/ui/src/views/Nodes.vue
- core/ui/src/views/settings/SettingsHttpRoutes.vue
- core/ui/src/views/settings/SettingsTlsCertificates.vue
Ref:
- https://github.com/NethServer/dev/issues/7383
- https://github.com/NethServer/dev/issues/7346
> fix: improve tls certificates & http routes pages

- core/imageroot/var/lib/nethserver/cluster/events/backup-status-changed/10node_monitor
Make sure the failed state is not overwritten.
Fixes NethServer/dev#7554
> fix(backup): correct alert logic

- core/imageroot/var/lib/nethserver/cluster/bin/send-cluster-backup
Reorganize the validation checks for system_id and auth_token to improve code clarity and maintainability.
https://github.com/NethServer/dev/issues/7594
> Reorder validation for system_id and auth_token clarity
